### ISSUE TITLE
Error with quotation marks in changelog

### ISSUE THREAD

**Issue by Phanx** [BigWigsMods/packager#10]
If the changelog contains quotation marks, and the `$releasedir` path contains spaces, uploading to WoWInterface fails.

https://github.com/BigWigsMods/packager/blob/master/release.sh#L1719

The problem is that the `changelog` field parameter isn't quoted. If I put this directly in the `curl` call:

`-F "changelog=<$pkgdir/$changelog"`

... then it works. It also works if I create a space-free symlink to the World of Warcraft directory and work under that instead of the real path.

I attempted several dozen variations on quote styles, escaping quotes, string concatenation, cat | sed to escape the actual quotes in the changelog text, etc., but only managed to shift the point of failure around.

Unfortunately escaping the changelog with HTML entities isn't a solution because the ampersand gets double-escaped (by curl or WoWI, I'm not sure which) and `&quot;` gets displayed literally on the website.

**Comment by nebularg** [comment]
I apparently missed that merging :scream:
