### ISSUE TITLE
Question: Correct way of handling localizations of externals

### ISSUE THREAD

**Issue by bullsei** [BigWigsMods/packager#101]
Hi, so i am currently trying to use the packager for including an external and i am wondering whats the best way of getting the localizations of the external to be included.

My main project and the external are both hosted on GitHub and both of them are using the BigWigs packager to create relaeses, both projects are currently using curseforge's localization system. 
Is there some way for the packager to download the fully packaged external from curseforge or 'Github releases' as a zip file which would include the localizations? Or maybe i am missing something obvious and there is a better way of handling a case like this.

**Comment by nebularg** [comment]
It would be best to just dump the localized strings into the addon so it's not using the localization system directly. If you're using something like LibStub, that'll also make sure the latest strings get loaded when you bump the minor after updating.

As far as the packager goes, I'd need to add a way to specify the project ID, but really, the less magic a lib has the better imo.

**Comment by bullsei** [comment]
Hey, thank you for the reply. Thats what i thought aswell, and i changed the addon accordingly and made it more general and put some of the localization work into the main addon. Feel free to close this issue
