### ISSUE TITLE
Keyword substitution not working in custom changelogs at Wowinterface

### ISSUE THREAD

**Issue by gi2k15** [BigWigsMods/packager#102]
I've created a custom changelog and used the tags @project-version@ and @project-date-iso@ in it. However, it wasn't replaced. I'm using Markdown style. You can check it at https://www.wowinterface.com/downloads/info26075-TinyLootMonitor.html#changelog

**Comment by nebularg** [comment]
Only `lua`, `xml`, and `toc` files are parsed for replacements

**Comment by gi2k15** [comment]
But the replacements are working in CF and Wago, with a changelog.md

**Comment by nebularg** [comment]
if you don't use a manual changelog, the default generated changelog will include that info. the script doesn't do any special processing for `md` files regardless of where it's being uploaded

**Comment by gi2k15** [comment]
But that's the thing, I'm using a manual changelog. Maybe CF and Wago are
doing the replacements, and not the script?

Em qui., 8 de jul. de 2021 00:01, Kyle Buller ***@***.***>
escreveu:

**Comment by nebularg** [comment]
You know, actually looking at the code, it does actually process `md` and `txt` files as well. Because the bbcode file isn't part of the package, it never get processed like the normal changelog. I'll look into it, thanks

**Comment by gi2k15** [comment]
Thank you for looking into it!

**Comment by Backupiseasy** [comment]
A few days ago I switched from BigWigsMods/packager@v1 to BigWigsMods/packager@v2 in my GitHub workflow for packaging my addon. Since then, "@project-version@" is no longer substituted with the actual project version, but with "@Project-Version@". You can see that here: https://github.com/Backupiseasy/ThreatPlates/releases. With 10.5.x I started to use v2. 
Does anyone have an idea why this is happening?

**Comment by nebularg** [comment]
The changelog has always been suppose to be left unchanged, but I can't think of a good reason for that so I'm going to let it get processed like a normal file

**Comment by Backupiseasy** [comment]
Thanks a lot!
