### ISSUE TITLE
Uploaded archive_name does not respect custom file name

### ISSUE THREAD

**Issue by QartemisT** [BigWigsMods/packager#108]
When setting a custom file name using the `-n` tag, it doesn't respect this when setting the `achive_name` variable, that gets sent as part of the `label` variable to curseforge/wow interface/wago.

**Comment by nebularg** [comment]
the label isn't the file name, obviously, I suppose I could add another switch for the label

**Comment by QartemisT** [comment]
Would be highly appreciated, due to the funky way we do CI, we sometimes issue rebuilds and attempt to set a new unique name for it via `-n`.
However due to the label getting reused, wago can fail after 5+ files with the same label.

**Comment by nebularg** [comment]
Updated -n so you can pass `-n "filename:label"` to set the label as well
