### ISSUE TITLE
Multiple TOC files support on subfolders too

### ISSUE THREAD

**Issue by hizuro** [BigWigsMods/packager#118]
It would be nice to add multiple TOC files support for subfolders.
One of my addons have subfolders that will be moved on packaging but their TOC files are not processed.

Thanks for thhis great script. ;-)

**Comment by nebularg** [comment]
Do you not use `move-folders` in the pkgmeta for that? it should pick up anything that ends up a root folder in the zip file

**Comment by hizuro** [comment]
I use move-folders in pkgmeta but toc files inside this folders are not processed with argument "release.sh -S".

**Comment by nebularg** [comment]
Can you link me to the project? It should be finding those tocs, so likely a bug

**Comment by hizuro** [comment]
curseforge git repo: https://repos.curseforge.com/wow/farmhud
currently i've added _TBC.toc and _Vanilla.toc in ./QuestArrow/ and ./TrailPath/ for packaging.

**Comment by nebularg** [comment]
Thanks for the report! should be fixed now
