### ISSUE TITLE
Question: Multipe game versions having different externals

### ISSUE THREAD

**Issue by bullsei** [BigWigsMods/packager#120]
Hey, i just wondered if its somehow possible to have support for multiple game packages with only one run of the script. Right now i am using 3 pkmeta files to package the same addon 3 times (Classic, TBC and Retail) since i didnt find a way to only include one additional external in Retail. This means i am downloading localizations and externals 3 times even tho it is only really necessary once. I figure this problem will get even worse when even more old expansions are re released. 

my current pkgmeta for retail looks like that:
`externals:
    Libs/LibStub: https://repos.wowace.com/wow/libstub/trunk
    Libs/CallbackHandler-1.0: https://repos.wowace.com/wow/callbackhandler/trunk/CallbackHandler-1.0
    Libs/AceConfig-3.0: https://repos.wowace.com/wow/ace3/trunk/AceConfig-3.0
    Libs/AceDB-3.0: https://repos.wowace.com/wow/ace3/trunk/AceDB-3.0
    Libs/AceDBOptions-3.0: https://repos.wowace.com/wow/ace3/trunk/AceDBOptions-3.0
    Libs/AceGUI-3.0: https://repos.wowace.com/wow/ace3/trunk/AceGUI-3.0
    Libs/AceGUI-3.0-SharedMediaWidgets: https://repos.wowace.com/wow/ace-gui-3-0-shared-media-widgets/trunk/AceGUI-3.0-SharedMediaWidgets
    Libs/LibPlayerSpells-1.0: https://github.com/AdiAddons/LibPlayerSpells-1.0
    Libs/LibRaces-1.0: https://repos.curseforge.com/wow/libraces-1-0
    Libs/LibSharedMedia-3.0: https://repos.wowace.com/wow/libsharedmedia-3-0/trunk/LibSharedMedia-3.0
    Libs/UTF8: https://repos.wowace.com/wow/utf8/trunk
    Libs/DRList-1.0: https://github.com/wardz/DRList-1.0
    Libs/LibDDI-1.0: https://repos.wowace.com/wow/libddi-1-0/trunk
    Libs/LibChangelog: https://github.com/BullseiWoWAddons/LibChangelog
    Libs/FlyPaper-2.0: https://github.com/Tuller/FlyPaper-2.0
    Libs/LibGroupInSpecT-1.1: https://repos.wowace.com/wow/libgroupinspect/trunk
`
the pkgmeta for TBC and classic look the same just without the LibGroupInSpecT-1.1 since this library doesnt support classic or TBC

the externals.xml like that 
`<Ui xmlns="http://www.blizzard.com/wow/ui/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.blizzard.com/wow/ui/ ..\FrameXML\UI.xsd">
	<Script file="Libs\LibStub\LibStub.lua"/>
	<Script file="Libs\LibRaces-1.0\LibRaces-1.0.lua"/>
	<Script file="Libs\UTF8\utf8.lua"/>
	<Include file="Libs\CallbackHandler-1.0\CallbackHandler-1.0.xml"/>
	<Include file="Libs\AceGUI-3.0\AceGUI-3.0.xml"/>
	<Include file="Libs\AceConfig-3.0\AceConfig-3.0.xml"/>
	<Include file="Libs\AceDB-3.0\AceDB-3.0.xml"/>
	<Include file="Libs\AceDBOptions-3.0\AceDBOptions-3.0.xml"/>
	<Include file="Libs\LibSharedMedia-3.0\lib.xml"/>
	<Include file="Libs\AceGUI-3.0-SharedMediaWidgets\widget.xml"/>
	<Script file="Libs\LibDDI-1.0\lib.lua"/>
	<Include file="Libs\DRList-1.0\DRList-1.0.xml"/>
	<Include file="Libs\LibPlayerSpells-1.0\lib.xml"/>
	<Include file="Libs\LibChangelog\LibChangelog.xml"/>
	<Script file="Libs\FlyPaper-2.0\LibFlyPaper-2.0.lua"/>
	 
	<Include file="Libs\LibGroupInSpecT-1.1\lib.xml"/>
	
</Ui>`
 
So i am trying to find a way of building 3 packages (locally and via GitHub actions) with only pulling localizations and externals once and just remove the not wanted exernal from the Classic and TBC package. Or maybe there is already a way to include the unwanted libary in all 3 packages but skip loading it on TBC and Classic?

**Comment by Nevcairiel** [comment]
One package that skips loading the unwanted libraries on versions that don't support them is currently the recommended approach.

To do that, you need to do the conditional loading inside your TOC file, because only TOCs can be different per version currently. The game supports loading Addon_Classic.toc, Addon_TBC.toc and Addon_Mainline.toc. You can either manually maintain those .toc files and only load the libraries you need, or you can let them be auto-generated based on processing tags to exclude libraries as needed.

Here is an example from myself:
https://github.com/Nevcairiel/Bartender4/blob/master/Bartender4.toc

I load LibClassicSpellActionCount in Classic only, and LibDualSpec only on Retail.

**Comment by bullsei** [comment]
Oh, very nice, thank you so much for that information and that instant reply. Somehow i managed to not know about this... I implemented it and it works like a charm :)
