### ISSUE TITLE
Handling missing CurseForge Game Versions with multi-TOC builds

### ISSUE THREAD

**Issue by Choonster** [BigWigsMods/packager#122]
CurseForge doesn't currently have a Game Version for 9.2.5, the latest Retail version at the moment is 9.2.0. I've just updated my AddOn to use `enable-toc-creation: yes` with `## Interface`, `## Interface-Classic` and `## Interface-BCC` tags in the TOC file; but because there's no Game Version for 9.2.5, the build is being uploaded to CurseForge with only 2.5.4 and 1.14.3 as the supported versions. Before I updated to the multi-TOC build, it looks like the packager was automatically falling back to 9.2.0 (the latest Retail version) when it couldn't find 9.2.5.

Would it be possible to automatically fall back to the latest CF Game Version for a game type in multi-TOC builds like what's done for single-TOC builds?

Multi-TOC: [TOC file](https://github.com/Choonster-WoW-AddOns/TargetNameplateIndicator/blob/1.43/TargetNameplateIndicator.toc), [Actions run](https://github.com/Choonster-WoW-AddOns/TargetNameplateIndicator/runs/6147065177)
Single-TOC: [TOC file](https://github.com/Choonster-WoW-AddOns/TargetNameplateIndicator/blob/1.42/TargetNameplateIndicator.toc), [Actions run](https://github.com/Choonster-WoW-AddOns/TargetNameplateIndicator/runs/5688802094)

**Comment by Choonster** [comment]
Sorry, I just realised that 9.2.5 hasn't been released yet; which would explain why CurseForge doesn't have a Game Version for it.

The fallback behaviour would still be nice to have for multi-TOC builds.

**Comment by nebularg** [comment]
That would be a good thing to add back in, I'll look into it
