### ISSUE TITLE
Wago Addons + WOTLK

### ISSUE THREAD

**Issue by QartemisT** [BigWigsMods/packager#126]
Hi there,

Just wanted to notify you that Wago Addons is now supported WOTLK builds using the `supported_wotlk_patch` argument.

The blizzard supported TOC suffixes for wrath is `[-_](Wrath|WOTLKC)`

:)

**Comment by Meorawr** [comment]
Are you sure that `WOTLK` is accepted as an alternative suffix? From what I'm looking at the client appears to be looking for `WOTLKC` instead.

**Comment by QartemisT** [comment]
My bad, good catch on the typo :)

**Comment by QartemisT** [comment]
There will need to be a fix much like there is `[[ "$wago_type" == "bcc" ]] && wago_type="bc"`, but for wrath -> wotlk, for the Wago support
