### ISSUE TITLE
[Help] Release descriptions getting wonky

### ISSUE THREAD

**Issue by TheLastDarkthorne** [BigWigsMods/packager#128]
Hello! It is my first time using this packager, I'm trying to update one of my favorite addons to use the packager (and then submit a PR to the author and see if they are interested). So far it seems to be working but the release description is getting wonky. It keeps putting in the title: `Addon name(@project-version@) ` and I dunno how to remove that project-version part of it or replace it with the latest tag name at least.

Can I get some guidance? Thank you! <3
This is the repo btw you can see the release there: https://github.com/TheLastDarkthorne/BetterWardrobe

**Comment by nebularg** [comment]
You can remove it from the title in the toc file, or add `changelog-title: Addon Name` to the .pkgmeta file
