### ISSUE TITLE
Found future tag, not packaging.

### ISSUE THREAD

**Issue by Jademalo** [BigWigsMods/packager#129]
I've recently been setting up some workflows to make both tagging and basic .toc updates easier. However, I'm running into a bit of a weird problem.

I've got [a workflow](https://github.com/Jademalo/SurroundFix/blob/master/.github/workflows/tag.yml) that automatically increments the tag and pushes it to the master branch. However, this tag can't run another workflow due to specific restrictions on workflows triggering workflows.
Because of this, in [my main workflow](https://github.com/Jademalo/SurroundFix/blob/master/.github/workflows/release.yml) I've got a section to specifically trigger the workflow on completion of the tag workflow as well. This works, and the workflow runs.

The problem is that for some reason, I get the following error 
`Found future tag "v4.1.2", not packaging.`
https://github.com/Jademalo/SurroundFix/runs/7334609690?check_suite_focus=true#step:3:30

I don't know why this is happening. The tag is on the Master branch, and everything should work. For whatever reason though, it's erroring out instead of creating the release.

Any ideas?

**Comment by Nevcairiel** [comment]
The current logic is designed to run on push workflows, otherwise the tag check won't work. Maybe another env variable can be used to detect that its not a push-initiated run?

GITHUB_EVENT_NAME = 'push' seems like it might do that?

**Comment by Jademalo** [comment]
> Chaining the workflows like that, it looks like you're basically packaging the commit before the tag, which is triggering a dup check (that message). If you add a step that manually checked out the tag again, that should probably fix it

https://github.com/Jademalo/SurroundFix/runs/7335658919?check_suite_focus=true#step:4:30
That didn't fix it, unfortunately :(


> The current logic is designed to run on push workflows, otherwise the tag check won't work. Maybe another env variable can be used to detect that its not a push-initiated run?
> 
> GITHUB_EVENT_NAME = 'push' seems like it might do that?

How exactly would I add that to the workflow? Or is this something that needs changed within the packager?

**Comment by nebularg** [comment]
looking at https://github.com/anothrNick/github-tag-action
![image](https://user-images.githubusercontent.com/1010803/178931008-9a0c047a-57a5-4025-9051-94f906815ed3.png)
that's the problem, it should at least have an option to create an annotated tag

hmhm

**Comment by Nevcairiel** [comment]
As far as I understand the documentation of the github environment variables, when you manually invoke the workflow, it'll not run in the context of the latest tag, but just run in the context of HEAD, hence the tag check will always fail. Only if a "push" action triggers the build will it actually run in the context of whatever was just pushed (eg. the tag). But the push action is ignored due to the rule of a workflow not triggering another.

Hence my suggestions above to only run the tag check on push actions - something that would need to be in the packager.

**Comment by nebularg** [comment]
yea, I guess just skipping it for anything but push would be an easy fix

**Comment by nebularg** [comment]
Ok, should be fixed for you with 41b0cab122d8db9b94c1a2567cfbc1c4da265500 now

**Comment by Nevcairiel** [comment]
9d09010965c0b9d5a8a15f9e72c6b97d166c60b5 accidentally removed the executable from from the script, i'm sure nebula will fix it when he notices and stops cursing.

**Comment by nebularg** [comment]
i was just checking where i messed that up x.x

**Comment by nebularg** [comment]
> what does the dup check actually do?

It's for people that package every commit. if you push both the commit and the tag within a short time, depending on how fast the runners get spun up, they can get published out of order. So before doing anything, the script checks if there is a tag that points at the commit with the assumption being you just want the tag packaged at that point.
