### ISSUE TITLE
Addon-Wrath.toc version not used if Addon.toc has a 3.x interface version

### ISSUE THREAD

**Issue by mooreatv** [BigWigsMods/packager#130]
If `-Wrath.toc` is present it should be what is used for wrath version and not whatever might be in the extension less .toc

Packager output
```
Game version: 1.14.3,9.2.5,2.5.4,3.3.0  # should be 3.4.0
[...]
Creating archive: DynamicBoxer-v3.09.02.zip (v3.09.02)
Uploading DynamicBoxer-v3.09.02.zip (1.14.3,2.5.4,3.3.0,9.2.5 release) to https://wow.curseforge.com/projects/323794
Error! (400)
{"errorCode":1002,"errorMessage":"Error in field `metadata`:\n* Invalid type. Expected Integer but got Undefined. Path \u0027gameVersions[2]\u0027, line 3, position 29."}


WARNING: No Wago game version match for "3.3.0", using "3.4.0"
Uploading DynamicBoxer-v3.09.02.zip (1.14.3,9.2.5,2.5.4,3.3.0 release) to Wago
Success!
```

`release.json` produced:

```json
{
    "releases": [
        {
            "name": "DynamicBoxer",
            "version": "v3.09.02",
            "filename": "DynamicBoxer-v3.09.02.zip",
            "nolib": false,
            "metadata": [
                {
                    "flavor": "classic",
                    "interface": 11403
                },
                {
                    "flavor": "mainline",
                    "interface": 90205
                },
                {
                    "flavor": "bcc",
                    "interface": 20504
                },
                {
                    "flavor": "wrath",
                    "interface": 30300
                }
            ]
        }
    ]
}
```

files: https://github.com/mooreatv/DynamicBoxer/tree/v3.09.02/DynamicBoxer

ps: I realize CF won't really support Legacy but the community packager should at least use the same rules as the game clients, ie Shadowlands uses -Mainline.toc when present, Classic era `-Classic.toc`, BCC `-BCC.toc` and WotLK recognize and uses `-Wrath.toc` while legacy clients only look at plain `Addon.toc`

**Comment by mooreatv** [comment]
Note that locally somehow it picks up the right version... despite same bash version (5.0.17(1)-release) and same processing order of toc files... seems something else is non deterministic

**Comment by mooreatv** [comment]
on ci
```
XXX 1185 : /home/runner/work/DynamicBoxer/DynamicBoxer/DynamicBoxer/DynamicBoxer-Classic.toc   11403
XXX 1185 : /home/runner/work/DynamicBoxer/DynamicBoxer/DynamicBoxer/DynamicBoxer-BCC.toc   20504
XXX 1185 : /home/runner/work/DynamicBoxer/DynamicBoxer/DynamicBoxer/DynamicBoxer-Wrath.toc   30400
XXX 1185 : /home/runner/work/DynamicBoxer/DynamicBoxer/DynamicBoxer/DynamicBoxer.toc   30300
XXX 1185 : /home/runner/work/DynamicBoxer/DynamicBoxer/DynamicBoxer/DynamicBoxer-Mainline.toc   90205
XXX 1199 : 1.14.3 9.2.5 2.5.4 3.3.0
```
while locally `DynamicBoxer-Wrath.toc` is last (this is in:
https://github.com/mooreatv/packager/blob/8c82d4cb55ed28d4d1c2c783faf58f13e9c9389a/release.sh#L1171-L1199
)

**Comment by mooreatv** [comment]
fix in #131 ptal

**Comment by mooreatv** [comment]
Example with the fix
https://www.curseforge.com/wow/addons/dynamicboxer/files/3895253
https://github.com/mooreatv/DynamicBoxer/releases/download/v3.09.03/release.json

Without, failed upload and
https://github.com/mooreatv/DynamicBoxer/releases/download/v3.09.02/release.json

**Comment by nebularg** [comment]
yea, a flavor specific file should definitely be the truth for what version is set when uploading. Glancing at the PR, I think a better fix would be to handle it in the do_toc func, but I'll take a closer look when I get home tomorrow.

Looks like I also need to fix release.json so it reflects the proper upload version 😵‍💫

**Comment by mooreatv** [comment]
I thought so too initially but the loop is repeated in set_build_version and that's where sorting to enforce order fixes the issue 

release.json is also fixed by #131 - only thing potentially would be to add a flavor `legacy` or `other` or some such for (my case) where the x.toc != x-Mainline.toc but I think supporting non standard client version is probably out of scope - it's just convenient to be able to have 1 zip that works with 5 client versions and none of them showing "out of date".

**Comment by nebularg** [comment]
yup, you were right. when I first looked at it I thought you were just sorting the versions, which seemed like an awkward way to fix it. I still want the root addon interfaces to take priority over move-folder stuff, so I'm going to rework it a bit more, but thanks for looking into it.

the json issue I had in mind was not using the fallback value, but thinking more about it, I'm not really sure how that should work if the different sites don't agree, so I suppose just using the determined version is fine

**Comment by mooreatv** [comment]
Thanks, will try your fix. Ps : my PR also had shellcheck fixes you might want to apply

**Comment by nebularg** [comment]
https://www.shellcheck.net/wiki/SC1004 ?

> (This warning was retired after v0.7.2 due to low signal-to-noise ratio)

**Comment by mooreatv** [comment]
maybe my shellcheck is old :)  but `skip_invalid=` undeclared too (https://github.com/BigWigsMods/packager/pull/131#discussion_r928292514)
