### ISSUE TITLE
Extremely slow packaging

### ISSUE THREAD

**Issue by Molkree** [BigWigsMods/packager#132]
Our addon has some big files, one of them being over 12 MB currently, and it always took a few minutes to package everything. However, [the last release](https://github.com/DFortun81/AllTheThings/runs/7461104631) we did it took 70 minutes to copy that one file:

![image](https://user-images.githubusercontent.com/12860284/180661963-62272896-224d-4ee0-b8a7-bb97506d250f.png)

Honestly, I didn't even notice that because it was a scheduled release. But I just did [a manual one](https://github.com/DFortun81/AllTheThings/runs/7489683512) and it's been copying that file for over half an hour already.

I have checked [the last release that went quick](https://github.com/DFortun81/AllTheThings/runs/7380899450), and it appears to use the same version of packager a22afa057b1474adbaac4953a10aaf523d6559d7 🤔

File size didn't change significantly, it's around 12.3 MB.

The only suspect I have now is the different environment in GitHub VM, the last quick one was ubuntu-20.04 20220710.1 and the slow one is 20220717.1. Here is [a changelog](https://github.com/actions/virtual-environments/commit/154099992ecb2fe92d55f51dc12827f47ee160da).

Any help on how the packaging can be sped up? Or maybe it really is a problem of VM environment and something that should be reported upstream?

**Comment by Nevcairiel** [comment]
The "Copying" phase is not only a copy, but also processes the files for keyword substitutions etc.
If your file does not actually use anything of that, you can significantly speed that process up by adding a "plain-copy" section into your pkgmeta. Same structure as eg. "ignore", and any files matching it will be copied straight-up, instead of being processed for keyword replacements.

**Comment by nebularg** [comment]
Yea, I've talked about this on the discord a bit, but the biggest slowdown is the EOL rewriting which is done in bash. I'm pretty close to just removing it all together and matching native for anything generated by the script. It is strange that the run time drastically changed, though.

But yea, if you have a bunch of big db files or stuff that doesn't need to be processed, you can use `plain-copy` like Nev said ([example](https://github.com/WeakAuras/WeakAuras2/blob/main/.pkgmeta#L47-L48))

**Comment by Molkree** [comment]
Thank you for suggestions, after "plain-copy"ing everything other than the .toc (the only place where we do version substitution) packaging only takes 7 seconds.

Coincidently, GitHub VM changed the environment again and I haven't tested it with the old copying so I can't say if it is still slow.

But I'm satisfied with the end result so closing this issue.
