### ISSUE TITLE
@localization string replacement does not handle errors from curseforge

### ISSUE THREAD

**Issue by mrbuds** [BigWigsMods/packager#133]
It happens that Curseforge servers infrastructure doesn't correctly handle request for @localization string replacement

Example in a WeakAuras alpha build <https://www.curseforge.com/wow/addons/weakauras-2/download/3911457>, this build took 14mn, and curseforge announced their server were unstable at the time.

Build log does not show an alert message and does not exit with error code.

```
    Copying: WeakAurasTemplates/Locales/itIT.lua
      Adding itIT/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/enUS.lua
      Adding enUS/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/esMX.lua
      Adding esMX/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/ruRU.lua
      Adding ruRU/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/ptBR.lua
      Adding ptBR/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/frFR.lua
      Adding frFR/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/deDE.lua
      Adding deDE/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/esES.lua
      Adding esES/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/zhTW.lua
      Adding zhTW/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/zhCN.lua
      Adding zhCN/WeakAuras/Templates
    Copying: WeakAurasTemplates/Locales/koKR.lua
      Adding koKR/WeakAuras/Templates
```

In file `WeakAurasTemplates\Locales\esES.lua`

```Lua
--@localization(locale="esES", format="lua_additive_table", namespace="WeakAuras / Templates")@
```
was replaced with
```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
```

or in same archive file `WeakAurasTemplates\Locales\zhTW.lua` string was replaced with an empty string

Script was called from github action script with `uses: BigWigsMods/packager@v2`

**Comment by Nevcairiel** [comment]
This sounds reasonable. Rather want your build to fail then have a broken package.

**Comment by nebularg** [comment]
I added a check so it'll show in the log, but I've run into a problem where I can't seem to pass on the error status to be able to exit the script 😒
