### ISSUE TITLE
Single TOC file failing using -classic tag

### ISSUE THREAD

**Issue by TimothyLuke** [BigWigsMods/packager#134]
I have a project setup for a single TOC which has been working forever.  I just merged in my wrath branch and action as Wrath Prepatch has hit PTR.  The TOC file has the following entries:
```
## Interface: 90205

## Interface-Classic: 11403
## Interface-BCC: 20504
## Interface-Wrath: 30400
```

When I build for retail, I get the following log:
```
Ignoring: luacov.stats.out
    Copying: pages/index.html (unchanged)
    Ignoring: PluginShell/PluginShell.toc
    Ignoring: PluginShell/loaded.lua
    Ignoring: PluginShell/macrosamplefile.lua
    Ignoring: PluginShell/README.md
    Ignoring: deploy.sh
    Copying: GSE_LDB/GSE_LDB.toc
      Creating GSE_LDB/GSE_LDB_Vanilla.toc [11403]
      Creating GSE_LDB/GSE_LDB_TBC.toc [20[50](https://github.com/TimothyLuke/GSE-Advanced-Macro-Compiler/runs/7683895419?check_suite_focus=true#step:9:53)4]
      Creating GSE_LDB/GSE_LDB_Wrath.toc [30400]
    Copying: GSE_LDB/LDBProvider.lua
```

The build from my wrath branch made the following:
```
Ignoring: luacov.stats.out
    Copying: pages/index.html (unchanged)
    Ignoring: PluginShell/PluginShell.toc
    Ignoring: PluginShell/loaded.lua
    Ignoring: PluginShell/macrosamplefile.lua
    Ignoring: PluginShell/README.md
    Ignoring: deploy.sh
    Copying: GSE_LDB/GSE_LDB.toc
      Creating GSE_LDB/GSE_LDB_Vanilla.toc [11403]
      Creating GSE_LDB/GSE_LDB_Mainline.toc [90205]
      Creating GSE_LDB/GSE_LDB_TBC.toc [20[50](https://github.com/TimothyLuke/GSE-Advanced-Macro-Compiler/runs/7465026874?check_suite_focus=true#step:9:53)4]
      Creating GSE_LDB/GSE_LDB_Wrath.toc [30400]
```

For the classic build it fails at the TOC.  
```
Copying files into .release/GSE:
    Ignoring: luacov.stats.out
    Copying: pages/index.html (unchanged)
    Ignoring: PluginShell/PluginShell.toc
    Ignoring: PluginShell/loaded.lua
    Ignoring: PluginShell/macrosamplefile.lua
    Ignoring: PluginShell/README.md
    Ignoring: deploy.sh
    Copying: GSE_LDB/GSE_LDB.toc
  Error: Process completed with exit code 1.
```

It looks like there is either a bug or the documentation needs to be updated to reflect the current state.

**Comment by Nevcairiel** [comment]
Ideally you want to use one build for all variants - which is why its generating 4 different TOC files in every build, which the game client loads as needed.

I'm not sure whats wrong with the classic build, but combining the TOC generation with flavor-specific builds is unusual and not really intended usage. Either you would use one build which can serve all 4 variants, or you would use different builds, but without the additional TOC files then.

**Comment by TimothyLuke** [comment]
Well this all worked 20 days ago - my last successful build.  It's only been today that this has occurred.  Wrath builds fine i haven't checked TBC independently.

The only reason for the multibuild has been feeding the Twitch Curse's machinery.  It wouldnt show multi-toc stuff to a classic client.

**Comment by nebularg** [comment]
Yea, sorry, this should never have worked. You’re mixing build processes and it should be catching that and erroring at the start. 

> The only reason for the multibuild has been feeding the Twitch Curse's machinery. It wouldnt show multi-toc stuff to a classic client.

The client has supported multiple versions for quite a while now without issue. Your “retail” step is the only one you need now-a-days.

**Comment by TimothyLuke** [comment]
What about WoWI - I have a classic and a retail id for those can I specify two WoWI's?

**Comment by nebularg** [comment]
WoWI supports multiple versions on a project just like CF and Wago

**Comment by nebularg** [comment]
I did fix the issue that caused this in ba3865fd1c2f39b055027e04ce8feaf8d3f65a12 so I'm going to close this, but if you have any questions feel free to ask

**Comment by Nevcairiel** [comment]
Shows 3.1.00 as latest in the box for me on your project. Might have still been processing the update when you looked.

**Comment by TimothyLuke** [comment]
Thanks @Nevcairiel i should have waited longer.  It’s not paranoia if Curse really is out to get you right?
