### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by arkayenro** [BigWigsMods/packager#138]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

line 2472 i think

**Comment by Molkree** [comment]
This should be resolved by #139

**Comment by nebularg** [comment]
Fix included in v2 now
