### ISSUE TITLE
Addon showing up as 1.0.0 instead of 10.0.0

### ISSUE THREAD

**Issue by whatisboom** [BigWigsMods/packager#140]
I just updated [my addon](https://www.curseforge.com/wow/addons/enchant-check-updated) that uses this script and updated the toc Interface value to 100000 and it was uploaded to curseforge as game version 1.0.0. I assume the script is looking at either the first 3 or 6 numbers in that string to determine the game version, but I am not a bash developer and have had not luck finding where that would be the case in your script.

**Comment by nebularg** [comment]
I assume you're using v1 or an outdated fork, switch to v2/this repo to use the latest version

**Comment by funkydude** [comment]
Your addon is using the old version of the packager, v1.
You can see that here: <https://github.com/whatisboom/EnchantCheck/blob/master/.github/workflows/release.yml#L39>

Change it to v2 (for stable) or to master (for bleeding edge) and your issue will be resolved.

**Comment by funkydude** [comment]
Pinning this for a while
