### ISSUE TITLE
GITHUB_OAUTH: Default to ${{ github.token }}? 

### ISSUE THREAD

**Issue by bloerwald** [BigWigsMods/packager#141]
For UX, it would be neat if the script defaulted `GITHUB_OAUTH` to `${{ github.token }}`.

I think 

```
    - run: GITHUB_OAUTH=${GITHUB_OAUTH:-${{ github.token }}} $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
```

should be enough for this. Hopefully, that will be masked.

**Comment by nebularg** [comment]
Not setting the GH token is the only way to avoid uploading releases so I'd rather automate it
