### ISSUE TITLE
.pkgmeta, github subfolder handling possible?

### ISSUE THREAD

**Issue by fubaWoW** [BigWigsMods/packager#143]
hi there,

I use a Subfolder of a Git Rep as an external Lib for my (our) AddOn but it seems it's not woking here?
At the Curseforge Packager i just used:
```yaml
externals:
   libs/LibInit:
      url: https://github.com/alarofrunetotem/LibInit.git/LibInit
      tag: latest
```
but here i get the error:
```
Fetching latest version of external https://github.com/alarofrunetotem/LibInit.git/LibInit/
remote: Not Found
fatal: repository 'https://github.com/alarofrunetotem/LibInit.git/LibInit/' not found
```

Also Tested with SVN URL like:
```
https://github.com/alarofrunetotem/LibInit/tree/master/LibInit
```
but also does not work

im doing something wrong?!

**Comment by nebularg** [comment]
as a work-around, can try using move-folders to keep the same structure (optionally ignoring stuff in the root you do not want packaged)
