### ISSUE TITLE
Packager ignores everything

### ISSUE THREAD

**Issue by Zottelchen** [BigWigsMods/packager#144]
Hi,
I am currently trying to build an action which builds my addon, but the packager just seems to ignore all files and thus generates a zip file with a changelog and nothing more. What am I doing wrong?

The pkgmeta file is as simple as it can be:

```
enable-nolib-creation: no

required-dependencies: 
  - adibags
```

Log:

```
Run $GITHUB_ACTION_PATH/release.sh -t dist

Packaging TestAddon
Current version: 1.0.0
Build type: retail non-alpha non-debug
Game version: 10.0.2

WoWInterface ID: b
Wago ID: c
GitHub: Zottelchen/adi-sl-test [token set]

Checkout directory: /home/runner/work/adi-sl-test/adi-sl-test/dist
Release directory: /home/runner/work/adi-sl-test/adi-sl-test/dist/.release

Copying files into .release/TestAddon:
    Ignoring: TestAddon.lua
    Ignoring: TestAddon.toc
    Ignoring: addon_supported_items.md
Generating changelog of commits into CHANGELOG.md
Creating archive: TestAddon-1.0.0.zip (1.0.0)
    adding: TestAddon/ (stored 0%)
    adding: TestAddon/CHANGELOG.md (deflated 51%)
Creating GitHub release: https://github.com/Zottelchen/adi-sl-test/releases/tag/1.0.0
Uploading TestAddon-1.0.0.zip... Success!
Uploading release.json... Success!


Packaging complete.
```

**Comment by Nevcairiel** [comment]
The only situation where anything gets ignored is if either its ignored through pkgmeta, or the repository has ignore rules setup that match those files.

Unfortunately your repository is not available to check further.

**Comment by Zottelchen** [comment]
Sorry, my bad, thought it was already public😅 https://github.com/Zottelchen/adi-sl-test

**Comment by Nevcairiel** [comment]
Your repository contains no files, so nothing to package? :)

The packager is designed to ignore any files that are not part of the repository, and are not part of its own inner workings to pull in from elsewhere.

What might work is if you create the extra files in a sub-directory, and then use the packagers move-folders command to move them where they need to be, instead of doing the move yourself before the packager runs (that way they become part of the packagers task, and no longer ignored). That way it should include them, I believe.

The other option is to specifically mark all the generated or externally obtained files in the "plain-copy" section of the pkgmeta, as that overrides implicit or explicit ignores.

**Comment by nebularg** [comment]
You could also commit empty files that your workflow replaces

**Comment by Zottelchen** [comment]
1. I was struggling with move-folders, probably because I am already using the -t to determine a directory to pack.
2. I could not find documentation on plain-copy?
3. Preemptively committing empty files brought me to the idea to just append this to my copy-action:
```
          git config --global user.email "gitaction@example.org"
          git config --global user.name "GitHubAction"
          git add *
          git commit --allow-empty-message -m ''
    ```

So now, it picks up the files, thanks for that already!
But now, it doesn't create a GitHub release any more. 🤔 I've also tried to use a non-empty message, but that doesn't seem to change anything (sample run: https://github.com/Zottelchen/adi-sl-test/actions/runs/3488229050/jobs/5836791589)

**Comment by Nevcairiel** [comment]
The git version now mismatches the github release, since you created a commit, so it no longer links them together.

**Comment by Zottelchen** [comment]
Oh, yeah, that makes sense.🙈 But just using `git add *` without committing seems to work! Thanks so much everyone!
