### ISSUE TITLE
How to package only for git?

### ISSUE THREAD

**Issue by N6REJ** [BigWigsMods/packager#147]
Right now I'm not ready to use wago or curse as I consider it in a "alpha" state.
I can't figure out how to make it "alpha" nor how to have it package even though I have both wago and curse blank.
I'm getting errors right now.
https://github.com/N6REJ/AdiBags_Bears_Ultimate/actions/runs/3786194791

**Comment by stamminator** [comment]
It seems like it's succeeding for you now. Did you figure it out?

**Comment by nebularg** [comment]
You simply don't include secrets for things you don't want to upload to
