### ISSUE TITLE
The label field is required error

### ISSUE THREAD

**Issue by furtrade** [BigWigsMods/packager#148]
I'm not sure why I'm getting this error, or how to fix it 😢 

Error! (422)  {"message":"The given data was invalid.","errors":{"label":["The label field is required."]}}

I'm also getting this:
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by nebularg** [comment]
Looks like you're no longer having issues, but I see what the issue was. Thanks for the report!
