### ISSUE TITLE
upload_curseforge() -- jq -e not extracting correct version_name

### ISSUE THREAD

**Issue by solagegrey** [BigWigsMods/packager#149]
Since WoW version 10.*, I have had to set the correct game version manually on CurseForge site, because it's been getting pushed as "1.0.0". (See below inserted screen snip.)
![upload_curseforge_snip](https://user-images.githubusercontent.com/94077372/214395717-2f5acc87-8611-450c-8b7a-c0a2521999e9.png)

I'm familiar with JSON, and not at all familiar with jq; but I believe the jq command in the upload_curseforge() function may need to be updated?

With some experimenting, I've been able to extract using jq -e ... with .apiVersion instead of .name:

**command:**
`jq -e --arg v "100005" --argjson t "517" 'map(select(.gameVersionTypeID == $t and .apiVersion == $v))' < file.txt`

**output:**
[
  {
    "id": 9711,
    "gameVersionTypeID": 517,
    "name": "10.0.5",
    "slug": "10-0-5",
    "apiVersion": "100005"
  }
]

file.txt is the output from `curl -s -H "x-api-token: <my-token>" https://www.curseforge.com/api/game/versions`

**Comment by ntowle** [comment]
See https://github.com/BigWigsMods/packager/issues/140.

**Comment by solagegrey** [comment]
thank you - I'll be sure to use v2 from now on
