### ISSUE TITLE
Needs better error codes

### ISSUE THREAD

**Issue by Gogo1951** [BigWigsMods/packager#153]
So I've set this up across half a dozen add-ons now, and all I did was copy and paste and it worked great. It's not working for me now and I don't know why. All I get is this message, and I don't know where to look up the exit codes to see what they mean.

> Error: Process completed with exit code 1.

https://github.com/Gogo1951/Open-Sesame/actions/runs/4275396709/jobs/7442716384#step:3:85

What makes this really frustrating, is that it was working (even with an "error" code), but now it's not and I don't know that I've changed anything on my side. It's possible I have... and just didn't realize it.

What I also really want, instead of more documentation, are just some examples I can directly copy and paste to set this up. I feel like it used to be a lot easier to get going. There needs to be a "simple lane" for people who don't want to deep dive into how this works.

Like I said, in the past, I could just set up secrets and drop in the action, and presto it worked. I've spent half a day spinning my wheels and it's crazy frustrating.

Also... I think some of the documentation is getting out of sync across the project read me, and the Wiki pages.

**Comment by Meorawr** [comment]
The log has more details - from the below I'd recommend looking at #152.

```
Updating GitHub release: https://github.com/Gogo1951/Open-Sesame/releases/tag/3.2.5
Error! (403)
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://docs.github.com/rest/reference/repos#update-a-release"
}
```

**Comment by Gogo1951** [comment]
So do I have to set up a GitHub secret now? I didn't used to have to do this.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/55365231/221417975-1ff48ece-9f6d-45de-96ec-cd639d34546a.png">

https://wowpedia.fandom.com/wiki/Using_the_BigWigs_Packager_with_GitHub_Actions

**Comment by Meorawr** [comment]
No - the issue specifically is that GitHub changed the default permissions for the automatic token made available to actions within new repositories:

https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/

As this is a personal repository you should be able to follow these instructions to grant it write access to publish the release.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository

**Comment by Gogo1951** [comment]
That is so frustrating for GitHub to change default behavior. Thanks! Testing it now. I would never have known to look there.

**Comment by Gogo1951** [comment]
That is so frustrating for GitHub to change default behavior. Thanks! Testing it now. I would never have known to look there.

**Comment by Gogo1951** [comment]
Seems to work now.

I literally spent 4 hours on this just randomly reading and mashing new things and probably pushed 20 dot update releases just to see if what I changed had any impact. Oof.

Thanks @Meorawr !

**Comment by Gogo1951** [comment]
It's working. Thanks!

https://www.curseforge.com/wow/addons/open-sesame

**Comment by Meorawr** [comment]
I've documented this a bit in a couple of locations now:

1. https://wowpedia.fandom.com/wiki/Using_the_BigWigs_Packager_with_GitHub_Actions#Troubleshooting
2. https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow

Would probably make sense to also put it in the README since I assume most people would look there first.
