### ISSUE TITLE
Deprecate BCC Support

### ISSUE THREAD

**Issue by QartemisT** [BigWigsMods/packager#160]
CurseForge have officially ended support for BCC versions, and attempting to upload with a BCC version will result in the following;

```
Uploading addon.zip (1.15.1,2.5.4,3.4.3,10.2.5 alpha) to https://wow.curseforge.com/projects/***
Error! (400)
{"errorCode":1009,"errorMessage":"Invalid game version ID: 9049 belongs to an invalid dependency."}
```

Given BCC is currently unused, I think it best to deprecate the usage of BCC, and ignore handling of those versions to 3rd parties.

**Comment by Meorawr** [comment]
Unsure if it's _official_ as it could just be an API bug on their end perhaps. The CF website is 50-50 on acknowledging that BCC game versions exist, as some dropdowns still list it and others don't.

**Comment by funkydude** [comment]
This is apparently unintended and should be getting fixed after I complained.
