### ISSUE TITLE
PACKAGER: CATA?

### ISSUE THREAD

**Issue by d4kir92** [BigWigsMods/packager#163]
hi, how can i use the packager to upload to cata?

![image](https://github.com/BigWigsMods/packager/assets/23246564/fa5f86d3-4ecc-4c43-88ce-18cea569c8a4)

i cant get it to work

**Comment by d4kir92** [comment]
![image](https://github.com/BigWigsMods/packager/assets/23246564/37269d73-18fc-48b1-9a5b-295511d355cd)

**Comment by nebularg** [comment]
I've updated the v2 tag so that it includes cata support

**Comment by d4kir92** [comment]
thx, also noticed that @master also works instead of @v2
