### ISSUE TITLE
Error when Interface contains a single value with a leading space

### ISSUE THREAD

**Issue by Lombra** [BigWigsMods/packager#166]
Hi,

Just updated to 2.3.1. Getting the following error on build:
```
/usr/local/bin/release.sh: line 1275: 10# 10 : syntax error in expression (error token is "10 ")
There was a problem setting the build version. Do you have a base "# Interface:" line in your TOC files?
```

Seems to happen when your interface is a single value with a leading space:
```
## Interface: 100100
```

Works:
```
## Interface:100100
```

**Comment by nebularg** [comment]
Are you running locally? what version of bash and awk are you using? I haven't seen this issue myself.

If you change line 1126 to `toc_version=$( awk -F: '/^## Interface:/ { print $2; exit }' <<< "$toc_file" | tr -d '[:blank:]' )` does it work?

**Comment by Lombra** [comment]
I am running it locally. (WSL Debian)
```
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
```
```
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan
```
Seems to work with the changes applied.

**Comment by nebularg** [comment]
mawk 1.3.3 is super old z.z you're still on buster? 1.3.4 seems to work fine.  oddly enough testing with [gnuwin32 mawk 1.3.3](https://gnuwin32.sourceforge.net/packages/mawk.htm) is fine parsing the interface but errors on getting the project title z.z
