### ISSUE TITLE
Setup / Release Questions

### ISSUE THREAD

**Issue by sahammer** [BigWigsMods/packager#168]
Hello!

First off, great work here! It was fairly easy to get up and running. I have a couple questions, specifically around Curse integration and releases.

How do I set the file "Name" on Curse" I want to use the full file name but it was just using `1.0.1-cata`

Also, what's the normal order of operations? I assume pull requets to main, then when ready to release - manually create a release on the repository with a tag?

**Comment by nebularg** [comment]
> How do I set the file "Name" on Curse" I want to use the full file name but it was just using `1.0.1-cata`

`-n ":{package-name}-{project-version}{classic}"` (or leave off the `{classic}` to only use your tag name, ie, drop the -cata)
 
> Also, what's the normal order of operations? I assume pull requets to main, then when ready to release - manually create a release on the repository with a tag?

Commit however you like, then to create a release you just push a tag. Assuming the packager is setup to package on tags and it has a github token, it'll create the github release for you.

**Comment by sahammer** [comment]
Sounds good!

I assume that is set here? 

```
- uses: BigWigsMods/packager@v2
  with:
    args: -n ":{package-name}-{project-version}{classic}"
```

**Comment by nebularg** [comment]
yup
