### ISSUE TITLE
Successful workflow, but missing folder

### ISSUE THREAD

**Issue by Dicebar** [BigWigsMods/packager#172]
Hi,

I'm the maintainer of [Raven](https://github.com/Dicebar/Raven), and I ran into a weird problem with our latest releases.

Despite nothing having changed in our [workflow file](https://github.com/Dicebar/Raven/blob/master/.github/workflows/main.yml) since early 2023, for whatever reason our Options addon isn't included in the release anymore.

The log (see below) does show that the options addon is moved to its own directory, but it's then not included in the zip-file that's uploaded to CurseForge.

If you have any insights and/or resolutions that would be greatly appreciated. Thanks!

```
Run BigWigsMods/packager@v2
Run if [[ -n "$WOWI_API_TOKEN" && "refs/tags/r663" == "refs/tags/"* && "true" == "true" ]] && ! hash pandoc &>/dev/null; then
fi
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
  WOWI_API_TOKEN: ***

Install pandoc
Run $GITHUB_ACTION_PATH/release.sh 
Reading project repository...done

Packaging Raven
Current version: r663
Previous version: r662
Build type: multi-version non-alpha non-debug
Game version: 10.2.6,4.4.0,3.4.3,2.5.1,1.15.2

WoWInterface ID: 18242 [token set]
GitHub: Dicebar/Raven

Checkout directory: /home/runner/work/Raven/Raven
Release directory: /home/runner/work/Raven/Raven/.release

Copying files into .release/Raven:
Fetching external: Libs/Ace3/AceAddon-3.0
Fetching external: Libs/Ace3/AceConsole-3.0
Fetching external: Libs/Ace3/AceEvent-3.0
Fetching external: Libs/Ace3/AceDB-3.0
Fetching external: Libs/Ace3/AceLocale-3.0
Fetching external: Libs/CallbackHandler-1.0
Fetching external: Libs/LibStub-1.0
Fetching external: Libs/LibSharedMedia-3.0
Fetching external: Libs/LibDBIcon-1.0
Fetching external: Libs/LibBossIDs-1.0
Fetching external: Libs/LibClassicDurations
Fetching external: Raven_Options/Libs/Ace3/AceGUI-3.0
Fetching external: Raven_Options/Libs/Ace3/AceConfig-3.0
Fetching external: Raven_Options/Libs/Ace3/AceDBOptions-3.0
Fetching external: Raven_Options/Libs/AceGUI-3.0-SharedMediaWidgets

Waiting for externals to finish...

Fetching latest version of external https://repos.curseforge.com/wow/libclassicdurations
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceAddon-3.0
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceConsole-3.0
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceLocale-3.0
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceDB-3.0
Fetching latest version of external https://repos.wowace.com/wow/libdbicon-1-0/trunk/LibDBIcon-1.0
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceEvent-3.0
Fetching latest version of external https://repos.wowace.com/wow/callbackhandler/trunk/CallbackHandler-1.0
Fetching latest version of external https://repos.wowace.com/wow/libsharedmedia-3-0/trunk/LibSharedMedia-3.0
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceDBOptions-3.0
Fetching latest version of external https://repos.wowace.com/wow/libstub/trunk
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceConfig-3.0
Fetching latest version of external https://repos.wowace.com/wow/ace-gui-3-0-shared-media-widgets/trunk/AceGUI-3.0-SharedMediaWidgets
Fetching latest version of external https://repos.wowace.com/wow/libbossids-1-0/trunk
Fetching latest version of external https://repos.wowace.com/wow/ace3/trunk/AceGUI-3.0
Using manual changelog CHANGELOG.md
Moving Raven/Raven_Options to Raven_Options

Creating archive: Raven-r663.zip (r663)
WARNING: No WoWInterface game version match for "2.5.1", using "2.5.4"
Uploading Raven-r663.zip (10.2.6,4.4.0,3.4.3,2.5.4,1.15.2) to https://www.wowinterface.com/downloads/info18242
Success!


Packaging complete.
```

**Comment by ntowle** [comment]
Your workflow file doesn't pass in a Curseforge API key to the packager. And so your log reflects that the packager is only uploading to WoWInterface. Do you have some separate workflow that's uploading to Curseforge?

**Comment by Justw8** [comment]
The Changelog here: 
https://www.curseforge.com/wow/addons/raven/files/5561202

also show's me this isn't generated by the default packager.

**Comment by ntowle** [comment]
I checked the zip that the BigWigs packager uploaded to WoWInterface and Raven_Options is present. So I think the BigWigs packager is working fine and your issue lies with whatever process you are using to upload to Curseforge. If you're using [Curseforge's webhooks](https://support.curseforge.com/en/support/solutions/articles/9000197281-automatic-packaging) you could try switching to the BigWigs packager instead and see if that resolves your issue.

**Comment by Dicebar** [comment]
Oof, that's the good stuff there. Thanks a lot, I'll get to work! :-)

**Comment by Justw8** [comment]
Keep in mind that when I downloaded the GitHub zip file - it was incorrect. So there might still be a bug here when a release it put up on github.

**Comment by Dicebar** [comment]
Got it working, thanks again! And sorry for not remembering that CurseForge was still set to its own solution. I added WoWInterface later, and it was honestly the only packaging method I remembered.

You're making an awesome package, it makes my life a lot easier👍

**Comment by Dicebar** [comment]
> Keep in mind that when I downloaded the GitHub zip file - it was incorrect. So there might still be a bug here when a release it put up on github.

We don't have releases on Github itself. Is that what you're referring to?

**Comment by Justw8** [comment]
https://github.com/Dicebar/Raven/tags

tags are packaged here, this looked the same as possibly your curseforge release.

**Comment by Justw8** [comment]
(this is not related to the packager, more a github thing)

**Comment by Dicebar** [comment]
It's kind of the same. We use tags to trigger releases. But the repo itself doesn't include the dependencies (libs) and has a slightly different structure.
