### ISSUE TITLE
name not matched zip error

### ISSUE THREAD

**Issue by helmuth99** [BigWigsMods/packager#173]
Hello, 
I am using your github action and i am getting the following error:

> [Creating archive: CronixUI_installer-v0.0.7.zip (CronixUI_installer-v0.0.7)
>   	zip warning: name not matched: CronixUI_installer
>   
>   zip error: Nothing to do! (try: zip -X -r /home/runner/work/CronixUI_installer/CronixUI_installer/.release/CronixUI_installer-v0.0.7.zip . -i CronixUI_installer)]

I tryed changing the repo-name to the addos name, the move-folder to the same name as the pachage-as in the .pkgmeta and the same name as the .toc file. I dont know what i am doing wrong that job fails. 
Any clarification what could cause it would be appriciated. 
Link to the repo: [https://github.com/helmuth99/CronixUI_installer](url)
Thank you in advance

**Comment by helmuth99** [comment]
Hello again,
if i start matching the move-folders (one of them) to the same name then the repo/package-as name, it now gives the error there is no toc. I looked at how ElvUI used this action and I just did it the same way as they did.

**Comment by nebularg** [comment]
the `package-as` has to be the name of the addon folder/toc, i.e.: `package-as: CronixUI_installer`

**Comment by helmuth99** [comment]
Ok it worked now, but i check my commits befor and i already had the same written befor and it failed, maybe I just overlooked something or I am loosing my sanity. Thank you for your answer.
