### ISSUE TITLE
svn: command not found

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/packager#177]
As the `ubuntu-latest` image for workflows have started rolling out 24.04 (as of Dec 5, [1]) and will be fully rolled out by Jan 17, users will experience this error:

```
svn: command not found
```

The subversion package was removed from the image, and `git-svn` was not provided as an alternative.

I've opened an issue with the image itself ([2]), but if it doesn't get resolved we'd have to look into providing this package ourselves.

[1]: https://github.com/actions/runner-images/issues/10636
[2]: https://github.com/actions/runner-images/issues/11219

**Comment by p3lim** [comment]
Seems unlikely that they'll add it back, it was pointed out to me that this is in their change logs:

> Removed from the Ubuntu 24.04 image due to maintenance reasons.

I'll update the action to add the package as a precautionary.

**Comment by p3lim** [comment]
Yeah, they won't add it back, my issue was closed quickly.

**Comment by nebularg** [comment]
Fixed in https://github.com/BigWigsMods/packager/commit/6b07139b9679523ba8128998eca5e107283e343b
