### ISSUE TITLE
Changelogs question

### ISSUE THREAD

**Issue by wardz** [BigWigsMods/packager#24]
Is there any way to disable changelog generation or have two seperate changelogs for classic and retail build?

So far im just using `manual-changelog` option but this is kinda annoying as it deletes all my previous changelog text on WoWInterface. And setting `wowi-create-changelog=no` doesn't seem to do anything.

**Comment by nebularg** [comment]
Using `manual-changelog` will always use that file if it exists, `wowi-create-changelog: no` will skip the auto-generated one when not using `manual-changelog`, which should result in no new changelog being set for the project.

If you want two different manual changelogs, you can create another pkgmeta file for your classic build and use `release.sh -m pkgmetafile`

**Comment by nebularg** [comment]
: not = 😜 lol, just noticed that

**Comment by wardz** [comment]
> If you want two different manual changelogs, you can create another pkgmeta file for your classic build and use `release.sh -m pkgmetafile`

I see. Thanks, I'll look into that.

> Using `manual-changelog` will always use that file if it exists, `wowi-create-changelog: no` will skip the auto-generated one when not using `manual-changelog`, which should result in no new changelog being set for the project.

I assume that will only work with WoWInterface and not Curseforge? I'd like to skip it for both, but anyways the solution above will probably work better.

**Comment by nebularg** [comment]
CurseForge requires a changelog when you upload, so you could just use generic, blank, or custom generated manual-changelog if you didn't want the auto-generated one
