### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by tekHudson** [BigWigsMods/packager#32]
When attempting to run locally I receive the following script error.

```
 tek (automate-release)
/mnt/d/World of Warcraft/_classic_/Interface/AddOns/DruidBarClassic » sh .release/release.sh
.release/release.sh: 167: .release/release.sh: Syntax error: redirection unexpected
```

**Comment by p3lim** [comment]
Run it with bash, not sh.

**Comment by tekHudson** [comment]
Ya I'm a dolt sometimes. Thanks 👍 💯

**Comment by p3lim** [comment]
Generally, well made scripts have a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) at the top of the script, allowing the system to determine the interpreter of the script when you execute it (which of couse requires the execution bit set on the file with `chmod +x release.sh`).
