### ISSUE TITLE
nolib upload curseforge support with API's parentFileID parameter

### ISSUE THREAD

**Issue by 2072** [BigWigsMods/packager#35]
Hello,

I noticed that the nolib packages are not uploaded to curseforge. From the commit log it was disabled several years ago because it could not be handled via Curse's API.
However now it seems that one can provide a parentFileID parameter to upload a file under another: 

https://authors.curseforge.com/knowledge-base/projects/529-api
```javascript
{
    changelog: "A string describing changes.", // Can be HTML or markdown if changelogType is set.
    changelogType: ["text", "html", "markdown"], // Optional: defaults to text
    displayName: "Foo", // Optional: A friendly display name used on the site if provided.
    parentFileID: 42, // Optional: The parent file of this file.
    gameVersions: [157, 158], // A list of supported game versions, see the Game Versions API for details. Not supported if parentFileID is provided.
    releaseType: "alpha", // One of "alpha", "beta", "release".
    relations: {
        projects: [{
            slug: "mantle", // Slug of related plugin.
            type: ["embeddedLibrary", "incompatible", "optionalDependency", "requiredDependency", "tool"] // Choose one
        }]
    } // Optional: An array of project relations by slug and type of dependency for inclusion in your project.
}
```
Could this be (re)implemented?

**Comment by nebularg** [comment]
I actually have a branch does that, but the original reason I removed it still existed: nolib archives were flagged as such internally and just parenting the file didn't get the curse client to recognize it. I'll poke someone to see if anything has changed there.

**Comment by nebularg** [comment]
Nope, still not possible.

**Comment by 2072** [comment]
Is it not possible to still include them even though the curse client doesn't recognize them as such? Do you mean that the curse client tries to install all the files at the same time?

**Comment by Nevcairiel** [comment]
The problem is that while you can flag files has having a parent, you can not flag them as being of the nolib variant, and thus the client will just never use them, making them rather pointless.

**Comment by 2072** [comment]
I see your point but maybe a simple fix for the Curse client would simply be to flag all child files ending with `parentname-nolib` as such. It might be just wishful thinking but if someone at Curse manages to implement that fix some day then existing package will benefit.
I know that -nolib packages are just used by developers but I still find this a good feature to not let disappear...
Is there a issue page for the Twitch client somewhere?
