### ISSUE TITLE
Sometimes the packager fails to detect that a Github release already exists

### ISSUE THREAD

**Issue by 2072** [BigWigsMods/packager#36]
Take a look at this build for example where two sets of packages are created (retail and classic):

https://travis-ci.com/2072/H-H-T-D/builds/125778315

After the retail package release creation, the packager creates the -classic packages and attempt to recreate the release instead of updating it. It seems to be a random issue since I made 3 other successful releases before...

It's probably Github's fault but could it be possible to trap this error and update the release instead of failing? (maybe by checking the date of the release, say if it's less than 5 minutes old...)

```javascript
Creating GitHub release: https://github.com/2072/H-H-T-D/releases/tag/2.4.9.3
Error! (422)
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "Release",
      "code": "already_exists",
      "field": "tag_name"
    }
  ],
  "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release"
}
```

**Comment by nebularg** [comment]
This should be fixed with 0d40d37
