### ISSUE TITLE
Feature request: option to ignore manual-changelog when there is no tag

### ISSUE THREAD

**Issue by 2072** [BigWigsMods/packager#37]
I like to have a "clean" changelog for beta and release that I write myself (where only end user visible changes are listed) but I also like to have commit logs for alpha packages.
The result is that I often forget to edit .pkgmeta when tagging a release or when pushing after a release...

Would it be possible to add a simple command line argument to ignore the .pkgmeta `manual-changelog:` directive when there is no tag?

Thanks!

**Comment by nebularg** [comment]
I've thought about adding an option for `manual-changelog` that would skip it for alphas, I like that more than adding a switch.

As a work-around, if you use something like Travis, you can just delete your manual changelog file for non-tags (eg: `[ -z "$TRAVIS_TAG" ] && rm -f CHANGELOG.md`) and it'll fall back to generating one.

**Comment by 2072** [comment]
great, thanks for the workaround :)

**Comment by nebularg** [comment]
You can also do this with multiple pkgmeta files, so I don't see myself doing anything additional here
