### ISSUE TITLE
Option to skip upload to WoWInterface

### ISSUE THREAD

**Issue by d87** [BigWigsMods/packager#38]
I want to upload dev builds only on github/cf, while still keeping ```## X-WoWI-ID```  in toc and i can't.
Thanks

**Comment by funkydude** [comment]
This is already the default behavior. Commits are uploaded to CF as alphas, tags are uploaded to all 3 sites as releases.

**Comment by nebularg** [comment]
And if you're doing weird things, you can use `-w 0` to unset it

**Comment by d87** [comment]
>-w 0 to unset it
Oh, good, thanks
