### ISSUE TITLE
changelog processing is different from curseforge packager (for manual changelog), on curseforge

### ISSUE THREAD

**Issue by mooreatv** [BigWigsMods/packager#40]
CF packager:
https://www.curseforge.com/wow/addons/dynamicboxer/files/2784081

changelog is as the original txt file
( https://github.com/mooreatv/DynamicBoxer/blob/master/ChangeLog.txt )

Bigwigs:
https://www.curseforge.com/wow/addons/dynamicboxer/files/2791311

lines are collapsed into paragraph
(and isn't doing markdown either)

is there an option to not process the manual changelog or to process it the same way as cf's packager?

**Comment by nebularg** [comment]
I can't do anything about how they process/display plain text, open a ticket with twitch support. Or use markdown.

**Comment by mooreatv** [comment]
you don't think it might have something to do with
https://github.com/BigWigsMods/packager/blob/master/release.sh#L2110
