### ISSUE TITLE
Error Fetching Externals Travis

### ISSUE THREAD

**Issue by doadin** [BigWigsMods/packager#47]
When an error occurs it exits with error 0 and shows as successful build instead of error 1.

https://travis-ci.org/doadin/Baggins/builds/610487289#L968

**Comment by nebularg** [comment]
Don't package in after_success.

**Comment by Nevcairiel** [comment]
To be accurate, https://github.com/BigWigsMods/packager/blob/master/release.sh#L1685 already returns a non-zero code on that error, but your Travis configuration ignores it

**Comment by doadin** [comment]
wow, im bad. sorry.

**Comment by nebularg** [comment]
no worries, it's @Stanzilla's fault

**Comment by Stanzilla** [comment]
😒
