### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by Knoot** [BigWigsMods/packager#48]
```
release.sh: command substitution: line 2093: syntax error near unexpected token `<'
release.sh: command substitution: line 2093: `                                 mapfile -t V < <( echo "$_cf_versions" | jq -r --argjson v "$game_version_id" '.[] | select(.id as $x | $v | index($x)) | .name' 2>/dev/null )'
```

**Comment by Knoot** [comment]
this error occurs when trying to upload the classic version, no problems with the retail

**Comment by nebularg** [comment]
What version of bash are you using?

**Comment by Knoot** [comment]
4.4.23(1)-release

**Comment by nebularg** [comment]
Do you have a link to the build online or do you run the script locally? I'm not sure what would cause that error, so it would be helpful to know the full build environment to try and reproduce the error.

**Comment by nebularg** [comment]
That's also a odd line number for that error to happen on, are you using a modified **release.sh**? Just clicking through some recent commits, I couldn't find one that would put the mapfile command on 2093

**Comment by Knoot** [comment]
I run this script on my computer with Windows 7 (x64), if you talk about it.
my only modification to the file is curse token
you're right, the line number is wrong, but I get exactly this error.

**Comment by Knoot** [comment]
I also noticed that my release.sh does not accept parameters when I open it through a shortcut, but if I pass the same parameters when called through bush, then everything is fine
