### ISSUE TITLE
localization error

### ISSUE THREAD

**Issue by Knoot** [BigWigsMods/packager#50]
```
 Copying: Locale/deDE.lua
    Adding deDE
    Error! Invalid output
           https://wow.curseforge.com/api/projects/313283/localization/export?lang=deDE&unlocalized=Ignore
```
This error is repeated for all languages.

If I copy this link, add the "&token={token}" token at the end and open it in the browser, then I see a page with the translation.
I copy the token that is recorded in release.sh cf_token, so I can be sure that the token is correct.
I did not make other changes to release.sh

Any ideas?

**Comment by nebularg** [comment]
That means you're hitting a redirect page due to CloudFlare or CurseForge problems. Testing it now I don't have any errors so hopefully it has resolved itself?

**Comment by Knoot** [comment]
No, the problem persists. I started getting this error more than a week ago. Since then, I have never managed to load localization via release.sh.

**Comment by Stanzilla** [comment]
We had that happen for WeakAuras as well but it it went away on its own.

**Comment by nebularg** [comment]
You can try using curl directly to see what it's pulling: `curl -s -H "x-api-token: [cf_token]" "[url]"`

That's all the script does to download the localization. Doing that with the url you posted works for me, so maybe it's something to do with the cdn you get routed to?

**Comment by Knoot** [comment]
@nebularg 
I did as you said, in return I get a Cloudflare page

**Comment by nebularg** [comment]
Hmm, so it's the anti-ddos protection and using &token= in the query string works, but not when it's sent as a header

**Comment by Knoot** [comment]
Do you have any ideas so that I can automatically load localization?

**Comment by nebularg** [comment]
since you run it locally, you can just edit the script on [line 1050](https://github.com/BigWigsMods/packager/blob/master/release.sh#L1050) to use the query string token, so 

`curl -s -H "x-api-token: $cf_token" "${_ul_url}"` becomes `curl -s "${_ul_url}&token=${cf_token}"`

**Comment by Knoot** [comment]
Unfortunately, this did not help.
if I understand curl syntax correctly, then the new line for tests should look like this:
`curl -s "https://wow.curseforge.com/api/projects/313283/localization/export?lang=deDE&unlocalized=Ignore&token={token}"`
right?
result still returns Cloudflare page

**Comment by nebularg** [comment]
Aw, you're right. For some reason it worked the first time I tried switching it around but now it doesn't 😖 Apparently they were having some real DDOS issues so they have aggressive protection on. The only thing I can think of is to use GitHub Actions or Travis to run it or try using a vpn in another region 😕

**Comment by Knoot** [comment]
thanks, great idea with vpn.

**Comment by Stanzilla** [comment]
There should be an error code on that CloudFlare page, could you tell me which one?

**Comment by Knoot** [comment]
@Stanzilla 
http://immage.biz/images/2020/03/31/SXTa.png

https://www.cloudflare.com/5xx-error-landing?utm_source=iuam

**Comment by Stanzilla** [comment]
@Knoot Are you from China by chance?

**Comment by Knoot** [comment]
No, I'm from Russia
