### ISSUE TITLE
Lua @non-retail@ tag not commenting out on build

### ISSUE THREAD

**Issue by niketa-wow** [BigWigsMods/packager#52]
I'm not sure if I'm doing something wrong, but I double checked the tag, but this keyword is not getting commented out in lua files. It works in the toc and the @retail@ keyword works in the lua files just fine.

`
    --@retail@
    local InterfaceIcons = self.GetFileDataRetail and self:GetFileDataRetail()
    --@end-retail@

    --@non-retail@
    local InterfaceIcons = self.GetFileDataClassic and self:GetFileDataClassic()
    --@end-non-retail@
`

The above is the code I have in my file (I had to add the check before the function call because the keyword not commenting this out, even though it commented out the file that contained the functions was breaking my addon.

The classic version ends up looking like this:

`
    --[===[@retail@
    local InterfaceIcons = self.GetFileDataRetail and self:GetFileDataRetail()
    --@end-retail@]===]

    --@non-retail@
    local InterfaceIcons = self.GetFileDataClassic and self:GetFileDataClassic()
    --@end-non-retail@
`

But the retail version just stays the same as the source code.

Again, I'm not sure if this is a bug or maybe me doing something wrong?

**Comment by niketa-wow** [comment]
Also, not sure why it's formatting my code like that, but hopefully you get the gist. No, I did not capitalize retail. It's just showing up weird on here.

**Comment by nebularg** [comment]
non tags should be block comments, they get uncommented if matched

**Comment by niketa-wow** [comment]
Oh, ok. Makes since it was me doing something wrong. Thanks for the quick response!

**Comment by nebularg** [comment]
:+1:

**Comment by p3lim** [comment]
Use \`\`\` to begin/end code blocks in markdown, three of them, not one.
