### ISSUE TITLE
Inconsistent handling of alpha/beta/release status

### ISSUE THREAD

**Issue by KyrosKrane** [BigWigsMods/packager#53]
(Full disclosure: I'm not a BigWigs developer, so this request is from my viewpoint as an external addon author. Thanks for providing this tool to everyone! :) )

The release script has some inconsistent handling of alpha, beta, and prerelease status across different upload targets. The base script only supports alpha (untagged) and release (any tag) settings, but it attempts to parse the tag later on and set alpha, beta, or prerelease status for individual repositories. This results in a file being mistagged across different repositories.

Here's the relevant code. First, at line 854, it sets alpha status based on whether the tag is present or not:

`	[ -n "$tag" ] && alpha="non-alpha" || alpha="alpha"`

At line 2126-2145, it sets the Curse upload status to alpha, beta, or release based on parsing the tag.

```
	# Upload to CurseForge.
	if [ -n "$upload_curseforge" ]; then
		# When packaging is triggered on your repository, the generated file’s release type will
		# automatically be set based on two factors:
		#   1) If configured to package all commits, the latest untagged commit will be packaged
		#      and will be marked as an alpha.
		#   2) Otherwise, when a tagged commit is pushed, it will be flagged as either alpha, beta,
		#      or release depending on the tag itself:
		#        - If the tag contains the word "alpha", it will be marked as an alpha file.
		#        - If instead the tag contains the word "beta", it will be marked as a beta file.
		# https://authors.curseforge.com/knowledge-base/projects/3451-automatic-packaging
		file_type="alpha"
		if [ -n "$tag" ]; then
			if [[ "${tag,,}" == *"alpha"* ]]; then
				file_type="alpha"
			elif [[ "${tag,,}" == *"beta"* ]]; then
				file_type="beta"
			else
				file_type="release"
			fi
		fi
```

Next, for Github, it's processed at line 2325. The status is set to pre-release only if the tag contains "beta" - alphas are uploaded to GH as production releases.

`		  "prerelease": $( [[ "${tag,,}" == *"beta"* ]] && echo true || echo false )`

The recommended fix is to move the CurseForge logic an initial status setting (effectively replacing line 854) at the start of the script. Determine early on whether this build is alpha, beta, or release. Then, update the CurseForge section to set the CF file_type value based on the setting. Finally, update the Github setting to tag both alpha and beta builds as prerelease.

The upshot of these changes is:

- If the build is untagged, treat as alpha.
- If the build is tagged, parse the tag for the "alpha" keyword and mark as alpha if found.
- If the build is tagged, parse the tag for the "beta" keyword and mark as beta if found.
- If the build is tagged and doesn't include the alpha or beta keywords, mark as release.

A related change may be required to the automated changelog handling (lines 1785-1813). The changelog should record changes as follows:
- If the build is alpha or beta, show all changes since last alpha, beta, or release (whichever is latest)
- If the build is release, show all changes since last release

This also resolves the issue of the release changelog only showing updates since the last alpha release.

**Comment by Nevcairiel** [comment]
Alphas without a tag should never upload to GitHub as-is, so I guess it would only apply if one tagged specifically as an alpha, which as far as I am aware is rather rare.

**Comment by KyrosKrane** [comment]
It's a common use case for me. I tend to make many small commits that aren't worth building, or would result in a broken addon. When I get to a logical stopping point or have coded something worth testing, I'll tag it as an alpha to make sure it builds right and to test that feature.

**Comment by nebularg** [comment]
I'll update it to treat alpha tags like an alpha build. As for changelog stuff, you can generate whatever you want as a manual changelog before packaging.

**Comment by KyrosKrane** [comment]
The changelog might actually correct itself if the alpha tag issue is corrected. I'll experiment with it once it's updated.

**Comment by nebularg** [comment]
Sorry, I did some work for this then got distracted 😒 I pushed 31eb488 and f6fc9f5 which fix most of your issues, although I left alpha build change logs as a cumulative list since the last (non-alpha) tag because that's just how they've always been.

**Comment by KyrosKrane** [comment]
I'm sorry, I owe you a test and review on this. I wasn't able to get to it this weekend. I'll try to complete it early this week.

**Comment by KyrosKrane** [comment]
OK, I've been using this new version of the packager exclusively with a new addon I'm writing. Here are my comments and observations.

Codewise, my only question is the one I left a comment on; you can see that linked above.

Functionally, this seems to work mostly as expected. Here are the scenarios I tested:

- An alpha-to-alpha or alpha-to-beta commit results in a changelog with changes since the last alpha. 
- A beta-to-beta release results in a changelog with changes since the last beta.
- A beta-to-release commit results in a changelog with changes since the last release. 
- A release-to-release commit results in changes since the last release.

Are there any other scenarios you'd like me to test?

**Comment by KyrosKrane** [comment]
If you'd like to see how the changelogs came out, here's the list for the addon I used for testing:
https://github.com/KyrosKrane/DigDug/releases

**Comment by nebularg** [comment]
> Are there any other scenarios you'd like me to test?

I actually cloned one of your addons to test things with 😛 But no, unless you have any other suggestions I consider it finished.

> Codewise, my only question is the one I left a comment on; you can see that linked above.

The GitHub release code is only hit for tagged commits, so while I could have used `$alpha`, the string check was the only relevant part and I decided to just do it again to match the beta check that was already there

**Comment by KyrosKrane** [comment]
Many thanks all around!
