### ISSUE TITLE
Question about action

### ISSUE THREAD

**Issue by Solor** [BigWigsMods/packager#57]
@p3lim 
Where do I put my WOWI api token when I use packager action?

According to README,

> release.sh will attempt to load environment variables from a .env file in the topdir or current working directory. You can also edit release.sh and enter the tokens near the top of the file.

Is this .env file public?

**Comment by nebularg** [comment]
You create a secret that is used by the workflow. Like the wiki says. https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
