### ISSUE TITLE
Error with awk in localization in the Alpine environment

### ISSUE THREAD

**Issue by Talryn** [BigWigsMods/packager#58]
I'm using the packager via a GitHub action and I receive the following error:

      Copying: Locale/enUS.lua
        Adding enUS
        awk: bad regex '^{"error': Invalid contents of {}

The localization is never added due to that error.

This error is caused because the version of awk with Alpine doesn't support the syntax in the existing code.  If I run my action referencing the previous commit before the update to the Alpine environment, it runs without errors and has the localization.

If you are going to use Alpine, I think the awk code needs to be updated to reflect the difference.

**Comment by p3lim** [comment]
Or keep it compatible with all other distros and just install the `gawk` package, no other changes needed.
Should probably make sure everything works, awk is not the only utility replaced by busybox alternatives (GNU variants is in package `coreutils`).

**Comment by nebularg** [comment]
I did check a few gnu things, forgot about awk

**Comment by Talryn** [comment]
Created a PR for it.  Adding gawk to the environment does fix the issue and I did not see any other problems.

**Comment by nebularg** [comment]
Thanks, I found some other quirks when testing the image, so hopefully everything is sorted now
