### ISSUE TITLE
Handling of Nested Keywords

### ISSUE THREAD

**Issue by StormFX** [BigWigsMods/packager#61]
I'm not sure if there is an easy fix or if it even matters in the long run, but nested keywords in certain file types can cause problems. Notably, XML. Take for example the following:

```xml
	<!--@no-lib-strip@-->
	<Include file="AceAddon-3.0\AceAddon-3.0.xml"/>
	<!--@retail@-->
	<Script file="LibDualSpec-1.0\LibDualSpec-1.0.lua"/>
	<!--@end-retail@-->
	<!--@end-no-lib-strip@-->
```

If one was packaging a no-lib, Classic release, you end up with malformed XML:

```xml
	<!--@no-lib-strip@
	<Include file="AceAddon-3.0\AceAddon-3.0.xml"/>
	<!--@retail@
	<Script file="LibDualSpec-1.0\LibDualSpec-1.0.lua"/>
	@end-retail@-->
	@end-no-lib-strip@--> <!-- Note the plain text. -->
```

I imagine that the simplest solution is to just not nest keywords in XML, etc, files. Issues are avoided easily enough by putting problematic lines in the ToC:

```txt
# Libraries
Libs\Libs.xml
#@no-lib-strip@
#@retail@
Libs\LibDualSpec-1.0\LibDualSpec-1.0.lua
#@end-retail@
#@end-no-lib-strip@
```

Though it might not be a bad idea to at least mention this is the wiki (unless it's there somewhere and I missed it). In any case, I just thought I'd mention it. Thanks!

**Comment by nebularg** [comment]
Yea, you can't nest XML comments. Pretty basic, but I can see someone being confused about it not working.

Also as an aside, you can just remove the `no-lib-strip` stuff. nolib packaging is purely legacy code. You can't set the proper relation to get the client to recognize the nolib package as such when uploading so it doesn't work like the CF packager.

**Comment by StormFX** [comment]
That's a good idea. I'm not doing no-lib packages anyhow. Thanks, K.
