### ISSUE TITLE
Packager Not Ignoring Files in Externals

### ISSUE THREAD

**Issue by StormFX** [BigWigsMods/packager#62]
While testing my widget library as an external in _Masque_, I noticed that the included external that was packaged includes files that I explicitly set to ignore in the `.pkgmeta` of the library. I'm no pro at shell, but I think I _might_ have it narrowed down to this bit of code in the `parse_ignore` function:

```shell
				if [ -d "$checkpath/$pattern" ]; then
					pattern="$copypath$pattern/*"
				elif [ ! -f "$checkpath/$pattern" ]; then
					# doesn't exist so match both a file and a path
					pattern="$copypath$pattern:$copypath$pattern/*"
				fi
```

If it's parsing the root add-on, the files on the ignore list exist relative to the root directory. However, when parsing externals, it's trying to find their ignored files in the root add-on directory as well. I tested this by echoing `$ignore` as it parsed and noticed that it listed a bunch of the same files multiple times.

I'm guessing that the issue is that there's no `else` section of that statement block that tells it to use the `$copypath$pattern` if the file _**does**_ exist, causing it fall back to just `$pattern`. This seems to fix it (like I said, I'm no pro at shell, so if it's bad, sorry. :p)

```shell
				if [ -d "$checkpath/$pattern" ]; then
					pattern="$copypath$pattern/*"
				elif [ ! -f "$checkpath/$pattern" ]; then
					# doesn't exist so match both a file and a path
					pattern="$copypath$pattern:$copypath$pattern/*"
				else
					pattern="$copypath$pattern"
				fi
```

**Comment by nebularg** [comment]
I suspect you need to fix your paths, but you'd have to show me your pkgmeta.

For example:

```yaml
externals:
  Libs/LibDeflate: https://github.com/SafeteeWoW/LibDeflate.git

ignore:
  - Libs/LibDeflate/*.md
  - Libs/LibDeflate/docs
  - Libs/LibDeflate/examples
  - Libs/LibDeflate/tests
```

results in

```
Fetching latest version of external https://github.com/SafeteeWoW/LibDeflate.git
Checked out 31e40e6
Copying files into .release/TestGit/Libs/LibDeflate:
  Ignoring: tests/dict_for_wow.txt
  Ignoring: tests/puff.c
	...
  Ignoring: tests/dictionary32768.txt
  Copying: libdeflate-1.0.2-1.rockspec (unchanged)
  Ignoring: docs/ldoc.css
	...
  Ignoring: examples/example.lua
  Copying: LibDeflate.toc
  Ignoring: README.md
  Ignoring: changelog.md
  Copying: LibDeflate.lua
  Copying: LICENSE.txt
  Copying: lib.xml
```

**Comment by StormFX** [comment]
I was under the impression that `packager.sh` was to read each _external_'s `.pkgmeta` and ignore the files that it specifies relative to _its_ (the external's) directory.

**Comment by nebularg** [comment]
That it should, but it's probably something I haven't run into and tested thoroughly :p

**Comment by StormFX** [comment]
That's what I'm saying in my first post. There's no `else` clause to that conditional so if `$pattern` is not a directory and it exists, it doesn't get `$copypath` prepended to it like it does in the other two cases. :P

**Comment by nebularg** [comment]
Yup, you are correct, sir

**Comment by nebularg** [comment]
Thanks

**Comment by StormFX** [comment]
Thank you! :)
