### ISSUE TITLE
Is that possible to add support for discord?

### ISSUE THREAD

**Issue by Solor** [BigWigsMods/packager#63]
Discord notification on release and upload released .zip file to discord 😎

**Comment by nebularg** [comment]
There are a [bunch](https://github.com/marketplace?type=actions&query=discord) of Discord actions that work for this. I'm not sure what benefit there is to adding it to the script itself.

**Comment by p3lim** [comment]
Yeah, use actions for that, or whatever else your CI provides if you're not using GitHub. People have so many different preferences when it comes to notifications, not to mention targets (Discord, Slack, email, custom solutions, +++), that it's unfeasable to try and support this in this project directly.
