### ISSUE TITLE
Not getting a Classic build following post October 3

### ISSUE THREAD

**Issue by TimothyLuke** [BigWigsMods/packager#64]
Hi All,

I had the following two lines in my .travis.yml file:

```
- curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash; if [[ $? != 0 ]]; then TRAVIS_TEST_RESULT=1; fi
- curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.5 -m .pkgmeta -w XXXXXX ; if [[ $? != 0 ]]; then TRAVIS_TEST_RESULT=1; fi
```

My build process would create two versions of the mod.  I used to get a 'version.zip' and a 'version-classic.zip'  I'm now getting two 'version.zip' files. None of the non-retail substitutions are occurring and the -w tag is also being ignored.  This was last working on a build I completed two days ago (October 3)

I did notice that there are some 'classic=' stuff in the new file.  Do I need to change the command line to get the old functionality back?

**Comment by nebularg** [comment]
Thanks, I should have my Travis test actually upload so I catch stuff like this
