### ISSUE TITLE
How exactly does the -g arg work?

### ISSUE THREAD

**Issue by Jademalo** [BigWigsMods/packager#68]
To build for classic, my project currently has this in the GitHub action;

      - name: Package and Release for Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g 1.13.5 -w 25252

I'm assuming that if -g is any version that is classic (1.13.x), then the `@non-retail@` tags will be used instead of `@retail@`, correct?

After poking around the script, I also noticed there is a shortcut for classic release in `-g classic`. Am I right in assuming that this reads the `@non-retail@` toc interface version to get the version if this argument is used?

Finally, is there any reason why `-g 1.13.5` is used in the wiki example for a classic build rather than `-g classic`? 
Are there any downsides to using `-g classic` over `-g 1.13.5`?

Thanks!

EDIT: Also this isn't strictly related to the above but I figure it's better asking here than opening another issue - Am I right in thinking that if the HEAD is not tagged, then it will build the current HEAD commit as an alpha build?

**Comment by Nevcairiel** [comment]
-g classic is rather new, which is likely why you won't see it used in many places yet.

**Comment by Jademalo** [comment]
Ah, that makes sense!
Is it alright to use as it is now, or is it still advised against?

**Comment by Nevcairiel** [comment]
It should be fine to use. But as always, validate your packages after making changes to the build process.

**Comment by Jademalo** [comment]
Alright awesome, thank you!

One other quick question if you don't mind answering, are there any situations where the script will overwrite what version is written in the toc?

```
if [[ ${BASH_REMATCH[1]} == "1" && ${BASH_REMATCH[2]} == "13" ]]; then
classic="true"
toc_version=$( printf "%d%02d%02d" ${BASH_REMATCH[1]} ${BASH_REMATCH[2]} ${BASH_REMATCH[3]} )
fi
```

I'm not good at bash, but this section of the script looks like it's forcing the toc_version to whatever is described in the -g argument, but it only seems to do that for classic.

Is there any reason why it doesn't do this for all game versions, or Is this basically ment as a failsafe for people who haven't got their .toc set up properly for classic release like the following?

```
#@retail@
## Interface: 90001
#@end-retail@
#@non-retail@
# ## Interface: 11305
#@end-non-retail@
```

Thanks!

**Comment by Nevcairiel** [comment]
The script is designed under the premise that with a dual-version build, retail is the default, hence no overwriting of the retail version.

**Comment by Jademalo** [comment]
Alright awesome, thanks!
