### ISSUE TITLE
$project-version is empty when using untagged git commit

### ISSUE THREAD

**Issue by Jademalo** [BigWigsMods/packager#69]
My head currently is a few commits ahead of the last tag, but the script doesn't seem to be able to create a version number based on the commit ID when not built against a tag.

The wiki states;

> `@project-version@` 
> Turns into an approximate version of the project. The tag name if on a tag, otherwise it's up to the repo. :SVN returns something like r1234 :Git returns something like v0.1-873fc1 :Mercurial returns something like r1234.

However, my release zip folder has no version attached, and the .toc version which is set by `@project-version@` is blank.
I'm using the -d argument, and nothing else.

A normal build built on a tag returns
```
Packaging SurroundFix
Current version: v3.6
Previous version: v3.5
Build type: retail non-alpha non-debug
Game version: 9.0.1
```
Whereas a build against an arbitrary commit returns
```
Packaging SurroundFix
Build type: retail alpha non-debug
Game version: 9.0.1
```

It seems that for whatever reason, when building from an arbitrary commit it doesn't populate the project-version value at all. 
I would have expected it to return a version based on the current git commit, or at the very least something based on the previous tag. Having it be totally blank definitely feels like there's an error there.

Checking out the tag builds as expected.

**Comment by nebularg** [comment]
The only way I can see `project-version` not being set is if there is an error from `git describe --always`. What is the output of that for you?

**Comment by Jademalo** [comment]
`v3.6-7-g5e389b5`, that seems to be working fine

**Comment by Jademalo** [comment]
Well this is extremely weird, running it manually on my debian machine gives me a blank `project-version`, but with the new github action I've set up the tag works as expected.

Is there any way I can make something more verbose to figure out why it doesn't work on my machine? As I said above, `git describe --always` works absolutely fine on it.

**Comment by nebularg** [comment]
Try `git describe --tags --abbrev=7 --exclude="*alpha*"`.  It looks like `--exclude` was added in 2.13.0, so that's probably it.

**Comment by Jademalo** [comment]
Ah, that might be it, my git version is 2.11.0
Weirdly I can't update it firther than that with apt

**Comment by p3lim** [comment]
You're still running Debian 9, version 10 has been out for over a year, 11 coming in a couple of months. Try upgrading your disto, or run this on a separate host/container.

**Comment by nebularg** [comment]
You can also use [stretch-backports](https://backports.debian.org) if upgrading isn't an option.
