### ISSUE TITLE
tag inside tag

### ISSUE THREAD

**Issue by doadin** [BigWigsMods/packager#72]
Hello, im not sure if this is just unsupported but I made this commit https://github.com/doadin/Plexus/commit/8f5bfcd8780a89c498d0061da7ef457622dc5dea to my repo and it resulted in a error.

```
--[===[@non-retail@

        if (showOffline or online) and (showWrongZone or curMapID == mapID) then

            hideGroup[subgroup] = nil

--@debug@

        elseif curMapID ~= mapID and not showWrongZone then

            hideGroup[subgroup] = (hideGroup[subgroup] or "") .. " ZONE"

        elseif not online and not showOffline then

            hideGroup[subgroup] = (hideGroup[subgroup] or "") .. " OFFLINE"

--@end-debug@

        end

--@end-non-retail@]===]
```

the end after `--@ end-debug@` was not removed from retail even though its before the `--@ end-non-retail@]===]` as if the `--@ end-debug@` closed the `--@ end-non-retail@]===]`.

**Comment by nebularg** [comment]
yea, the packager isn't context aware so you have to be careful how you nest replacements like that

**Comment by nebularg** [comment]
probably wouldn't hurt to change the number of `=`s for other replacements to make it safer, though
