### ISSUE TITLE
--@non-retail@  / --@end-non-retail@ not being commented out when packaging retail

### ISSUE THREAD

**Issue by typicalzergling** [BigWigsMods/packager#73]
I have some code that needs to be split between packaging retail and non retail. When building classic it correctly adds comments between the retail / end-retail tags, but when building retail it does not comment out the non-retail tags. I've tried building both without specifying a game version and when specifying game version as the latest retail (9.0.1) and neither works to ever comment out code bracketed by non-retail / end-non-retail tags.

Am I missing some magic sauce to make retail builds not include non-retail tags?

**Comment by Nevcairiel** [comment]
non-retail is a reverse tag (as "non" tags are), which means it would only remove commenting from it and enable the code in classic builds instead, and not comment out existing code.

**Comment by typicalzergling** [comment]
I see thank you, I was holding it wrong :)  That actually makes a lot of sense so you don't have classic stuff in development retail builds. I was able to get it to work by block commenting the non-retail and end-non-retail. PEBKAC problem solved :)
