### ISSUE TITLE
Not updating WoWUI or Curse

### ISSUE THREAD

**Issue by schnoggo** [BigWigsMods/packager#74]
I must be missing something obvious.
@p3lim 
I'm setting up the workflow on [SimpleCoords](https://github.com/schnoggo/SimpleCoords)
And I created a release.
Updated GitHub, but I don't see any action or errors relating to WoWUI or Curse.

I set up the secrets (at the project level).

Thoughts?

**Comment by Nevcairiel** [comment]
You need to tell it which projects on Curse or WoWI to upload to. The easiest method is to include the project IDs in the TOC file, as mentioned in the packager README in the 4th block, or you can specify the project ID with command line options when invoking the packager.

**Comment by schnoggo** [comment]
I did that as well. 
## X-Curse-Project-ID: 298475
## X-WoWI-ID: 7814

But like I said, it's not doing anything for those platforms.
Is there a verbose option to log errors?

**Comment by Nevcairiel** [comment]
I don't see those lines in your repository.

**Comment by schnoggo** [comment]
Well that's odd. I added them in the GitHub UI, and I see them in my local pull.
But you're right. Not showing up.
Thanks for the lead.
