### ISSUE TITLE
Set changelog title

### ISSUE THREAD

**Issue by Molkree** [BigWigsMods/packager#78]
[Addon](https://github.com/DFortun81/AllTheThings) I'm trying to use packager with has icons in its title, defined in [.toc](https://github.com/DFortun81/AllTheThings/blob/master/AllTheThings.toc#L4):
```
## Title: .|TInterface\Addons\AllTheThings\assets\logo_32x32:0|t AllTheThings |TInterface\Addons\AllTheThings\assets\logo_32x32:0|t
```
It results in the fancy title in game:
![image](https://user-images.githubusercontent.com/12860284/108110112-db877580-70a3-11eb-9e4d-362786802631.png)

But it also results in the not so fancy title in the auto changelog:
![image](https://user-images.githubusercontent.com/12860284/108110192-f659ea00-70a3-11eb-8a70-86ddb4bd0848.png)

Is there an option I'm missing that could help override Title from the .toc (without the use of manual changelog)?
If not then I'm proposing to add such an option, either as a new field in .pkgmeta or just as an extra option for the packager itself. Or modify Title parsing in packager to exclude icons.

**Comment by Tuller** [comment]
I wonder if colorized text would also have issues. Not that anyone really should do either.

**Comment by Molkree** [comment]
@Tuller, I think color is being ignored, at least this part of the Title [parsing](https://github.com/BigWigsMods/packager/blob/master/release.sh#L887) looks like it: `-e 's/|c[0-9A-Fa-f]\{8\}//g' -e 's/|r//g'`.

**Comment by nebularg** [comment]
It would be easy to strip the textures as well, but why do you have that period as the first char?

**Comment by Molkree** [comment]
I think because texture sorts at the very bottom of the addon list and period puts you on the top. That period is why I'd prefer the ability to set whole title instead of simply filtering out textures :D

**Comment by Stanzilla** [comment]
That's some really sketchy behavior that I don't think should be supported. Just my 2ct, don't do that.

**Comment by Molkree** [comment]
@Stanzilla, what is? Putting textures in the title? Putting period in the front?
Either one wasn't my decision, I would remove the dot and first icon so it just sorts alphabetically.
Or option to set changelog title not from .toc Title?

**Comment by Stanzilla** [comment]
The dot, the texture is whatever, I don't like it but trying to an addon show up at the top of the list is just cheeky.

**Comment by funkydude** [comment]
>I would remove the dot and first icon so it just sorts alphabetically.

This is exactly what I was about to suggest.
We should add support for stripping icons and you should make that change so that it sorts correctly in the list. Currently with or without the period it's not "correct" in the list.

This seems like a reasonable middle ground.

**Comment by nebularg** [comment]
I don't think textures should be used in the title, but wow allows it so /shrug. I added a way to set the changelog title in the pkgmeta, you can use `changelog-title: AllTheThings` now

**Comment by Molkree** [comment]
Thank you!
