### ISSUE TITLE
line 1255: wait: pid <N> is not a child of this shell

### ISSUE THREAD

**Issue by Phanx** [BigWigsMods/packager#8]
Posting here because my understanding of Linux and bash is insufficient to have any idea how to investigate this problem. Verified that it happens with your version (at [c716789](https://github.com/BigWigsMods/packager/commit/c71678966915ac87728486acbb627de36005af34)), so it's not related to any changes I've made.

`./release.sh: line 1255: wait: pid 15572 is not a child of this shell`

Here's the command I entered:

`./release.sh -t ../Broker_Reincarnation -d`

And here's the full output:
https://gist.github.com/Phanx/00df7dd02800a648600a5c1c7705ae6a

If I go check the `.release` directory, all the files (including externals) are in the proper location. If I comment out lines 1255-1257 and re-run the command, no error is given, and a ZIP file is successfully created with all externals.

```
# Handle external repo errors
set -o monitor
handle_chld() {
	for i in ${!external_pids[*]}; do
		pid=${external_pids[i]}
		if ! kill -0 $pid &>/dev/null ; then
#			if ! wait $pid; then
#				external_error=1
#			fi
			unset external_pids[i]
		fi
	done
}
trap handle_chld CHLD
```

The related .pkgmeta file can be seen here:
https://github.com/Phanx/Broker_Reincarnation/blob/master/.pkgmeta

The same thing happens with any other addon I tested on; I just used this one for the ticket since its list of libs is the shortest.

Linux Mint 17.3 (based on Ubuntu 14.04) with bash 4.3.11. If any other details would be helpful, let me know what they are.

**Comment by nebularg** [comment]
If you delete the kill check does it work normally? I'll have to look into how I do that a bit closer, seems bash 4 causes a race condition.

**Comment by Phanx** [comment]
Seems to work without the `kill` check (leaving the `wait` check and `unset` lines intact).
