### ISSUE TITLE
Handle 'Interface-Retail' in TOC

### ISSUE THREAD

**Issue by p3lim** [BigWigsMods/packager#82]
Ref https://github.com/BigWigsMods/packager/commit/2963e10c110324e3dad8357f7c7e4a23caacec24

This should also handle `## Interface-Retail: ...` for those who primarily play/develop on other versions than retail, as suggested in https://github.com/Stanzilla/WoWUIBugs/issues/68.

**Comment by nebularg** [comment]
Ah, missed that case. `## Interface-Retail` currently only gets used if you don't have any `## Interface: ...` line
