### ISSUE TITLE
game_version variable taint

### ISSUE THREAD

**Issue by QartemisT** [BigWigsMods/packager#83]
When uploading to WowInterface, the game_version varaible gets tained here: https://github.com/BigWigsMods/packager/blob/master/release.sh#L2306

Which when uploading to wago, causes it to use the tainted variable as a release, which wago then marks as invalid.

Logs:

```
Uploading <Addon>-bc.zip (2.5.1 release) to https://wow.curseforge.com/projects/<id>
Success!

Uploading <Addon>-bc.zip (2.05.1) to https://www.wowinterface.com/downloads/info<id>
Success!

Uploading <Addon>-bc.zip (2.05.1 release) to Wago
Error! (422)
{"message":"The given data was invalid.","errors":{"supported_bc_patch":["The selected supported bc patch is invalid."]}}
```

**Comment by MysticalOS** [comment]
Just a note, wow interface has already fixed invalid version number on their end so the issue will be fixed by that alone, but prob still worth fixing the taint here
