### ISSUE TITLE
Feature Request: Skip gitignore entries

### ISSUE THREAD

**Issue by Industrial** [BigWigsMods/packager#86]
Hi!

I'm writing an addon in MoonScript so I have a `src` directory and a `build` directory. My `build` directory is in the `.gitignore` file and this causes the contents not to be zipped. Right now I am mitigating this by running a `git add` in the Github Actions before doing the packager step.

I would like to request an option for listing entries that are ignored by SCM but required for packaging. To be honest, I don't think it should look at the gitignore entries at all but look at the ignored entries in the `.pkgmeta` only.

**Comment by nebularg** [comment]
> I would like to request an option for listing entries that are ignored by SCM but required for packaging.

I could see a .pkgmeta directive for adding an untracked/ignored directory to the build list, but you're already accomplishing this with git add

> To be honest, I don't think it should look at the gitignore entries at all but look at the ignored entries in the `.pkgmeta` only.

People do build locally
