### ISSUE TITLE
skip_copying also sets skip_upload to true

### ISSUE THREAD

**Issue by ascott18** [BigWigsMods/packager#90]
In my builds, I have a separate step for GH release creation that uses a trimmed version of my manual changelog (similar issue to #71). A while back, I used to be able to run this with options `-o -e -c -l` to avoid re-fetching externals, re-localizing, re-copying files, and so on. Unfortunately, a change was made to cause option `-c` (skip_copying) to also turn off uploading entirely: https://github.com/BigWigsMods/packager/commit/cf2276c9d4d7147a4339b323ed0e0072be574fee#diff-8bc94a3006768345d17c827c0bb5840e6e4daee6de1c2b1ea672f53f162d171dR117

Looking at that commit message, it feels like this change was maybe unintentional? In any case, it would be nice to be able upload a different changelog to the GH release without having to re-build the entire addon.

**Comment by nebularg** [comment]
> Looking at that commit message, it feels like this change was maybe unintentional? 

Who knows, probably slipped in when I was testing stuff and I figured it was fine :p
