### ISSUE TITLE
WowInterface Changelog not appearing properly

### ISSUE THREAD

**Issue by CDAGaming** [BigWigsMods/packager#91]
Earlier today, I decided to begin publishing my addon to WowInterface. One immediate notice is that the auto-changelog is not coming through cleanly to WowInterface, as the below image represents:

![image](https://user-images.githubusercontent.com/16328918/116159945-bf610f80-a6b6-11eb-9e29-d5684c70b7a2.png)

**Comment by Stanzilla** [comment]
You have to message Dolby so he enabled Markdown support on your project, that's still not rolled out globally yet afaik.

**Comment by nebularg** [comment]
Indeed, it looks like the project is set to use markdown, so you'll have to add `wowi-convert-changelog: no` to your .pkgmeta

**Comment by nebularg** [comment]
I noticed this wasn't working as I thought it would, should be good now. Now I just need someone to poke dolby into finishing markdown support so I can do things automatically.
