### ISSUE TITLE
Upload to wowinterface doesnt seem to be working

### ISSUE THREAD

**Issue by caffeineaddiction** [BigWigsMods/packager#94]
@p3lim
I am a noob to  writing addons / git workflows / packager ... but I have worked with Jenkins professionally in the past and get the gist of what is going on.

I have the following yaml file: https://github.com/caffeineaddiction/sudo/blob/main/.github/workflows/build.yml

It seems to upload to curse just fine but will not work with wowinterface.  I have verified that my api token is valid and does work with this site per cli https://i.imgur.com/rFAImh1.png

I do not see any errors in the workflow logs ...

Unsure if this is a bug w/ packager or with WoWInterface.

**Comment by Nevcairiel** [comment]
Did you ever tag a release with the WoWI Project ID present in the TOC? Only tags are uploaded to WoWI, and your 1.0.8 tag did not include the information yet.

**Comment by caffeineaddiction** [comment]
one moment, testing
