### ISSUE TITLE
[help] "No Git, SVN, or Hg checkout found." error on action

### ISSUE THREAD

**Issue by sandervspl** [BigWigsMods/packager#95]
I'm getting the following error when running my Github Action

```
No Git, SVN, or Hg checkout found.
Error: Process completed with exit code 1.
```

Action: https://github.com/sandervspl/BuffTimers/runs/2619301060?check_suite_focus=true
Repo: https://github.com/sandervspl/BuffTimers

I'm quite confused because looking at the release.sh code, it failed to find the `.git` folder. I don't know how to debug this, honestly. Anyone have experience with resolving this?

**Comment by sandervspl** [comment]
Resolved by adding this step

```
- name: Clone project
        uses: actions/checkout@v1
```

I'm a bit confused as I don't see this step in other projects, but it works for me.

**Comment by p3lim** [comment]
It's documented in the wiki linked in the readme, and is something everyone using this project as a GitHub action must use, and is using.
