### ISSUE TITLE
release.json is missing assets for multiple-client builds

### ISSUE THREAD

**Issue by Meorawr** [BigWigsMods/packager#96]
The release.json file is being generated such that it only contains information about the last packaged zip asset in setups where the packager is executed once per targeted game client. This appears - based on the timings of the examples below - to have possibly been caused by the fix applied for #93 (10b47034f1462d0f9f1868a3c757adc8664ab4cc).

An example can be seen on the TRP3 project with these two releases ([workflow](https://github.com/Total-RP/Total-RP-3/blob/main/.github/workflows/release.yml)):

- [v2.3.5-beta1](https://github.com/Total-RP/Total-RP-3/releases/tag/2.3.5-beta1) (9 days ago): [release.json](https://github.com/Total-RP/Total-RP-3/releases/download/2.3.5-beta1/release.json)
- [v2.3.5](https://github.com/Total-RP/Total-RP-3/releases/tag/2.3.5-beta1) (7 days ago): [release.json](https://github.com/Total-RP/Total-RP-3/releases/download/2.3.5/release.json)

[Another example is the most recent WA release](https://github.com/WeakAuras/WeakAuras2/releases/tag/3.4.1) - theirs only lists the BCC package in the release.json file, which is the last one processed in their workflow.

**Comment by nebularg** [comment]
The thing I fixed in 5fc8ce731c13ba89d1ed0ab62483fd78bbbff110?

**Comment by Meorawr** [comment]
I never said I was a smart person. That'd probably explain my confusion when I was thinking I saw something _else_ regarding that much more recently.

**Comment by nebularg** [comment]
😜
